#This verb list is for a prophecy generator
#Therefore, all the verbs will be in futrue tense.
#Also, all the verbs will be lower case. 
verb_list = [ 
    "dance",
    "shatter",
    "die",
    "kill",
    "execute",
    "laugh",
    "sing",
    "cry",
    "run",
    "jump",
    "fall",
    "fly",
    "swim",
    "sink",
    "rise",
    "walk",
    "whisper",
    "scream",
    "shout",
    "silence",
    "fight",
    "battle",
    "duel",
    "clash",
    "argue",
    "destroy",
    "avenge",
    "pray",
    "fight",
    "crumble",
    "run",
    "dine",
    "dig up",
]