creepy_occurances_list = [
    "The party randomly finds an ancient portrait that accurately depicts one of them",
    "You find a mirror in which the reflections seem to move more slowly than the objects creating them",
    "A fragile object falls of a table or shelf shattering ato the ground seemingly without a cause",
    "A random person comes up to the party on the street and growls at them ferally before marching off in a different direction",
    "A black cat crosses the part's path an meows at them in a sinister fashion",
    "Random low-hanging mist creeps around the area for a few minutes in thin tendrals before dissipating. The mist comes and goes without apparent cause.",
    "A door opens and closes nearby for no apparent reason",
    "For a brief moment, you hear what is unmistakably the wracking sobs of an adult woman. The source never becomes apparent",
    "A nearby portrait or bust begins to weeb blood. When a creature turns to fully inspect the phenomenon, it is gone and no evidance remains",
    "You hear the giggling of children that echoes from different places around the room. The source is never identified",
    "Fresh food suddenly rots, milk curdles and water turns mucky and foul",
    "All around the party they can hear scratching in the walls that fades as suddenly as it begins",
    "For a brief instant, you hear disembodied voices speaking over one another, growing louder and louder, before they suddenly stop",
    "All of a sudden, a random member of the party begins to laugh maniacally without cause",
    "Greenish-black ooze starts to creep through the cracks in the walls and the temperature in the room drops rapidly",
    "All of a sudden, all the NPCs around the party stop and stare without speaking. After a few seconds, life continues around them as if nothing ever happened",
    "One random member of the party has a sudden graphic vision of their own death",
    "The sound of dripping water can be heard everywhere aroudn the party and they are spattered with droplets of blood. The blood quickly disappears as the dripping sound fades away",
    "The party can hear a pack of dogs barking in the distance. The sound chills them to their bones but no dogs are ever seen",
    "Exposed sources of flame suddenly gutter and flicker as if exposed to a strong gust of wind, but there is no wind",
    "A large number of small spiders descend from the ceiling on stands of sparkly webs.",
    "A mosquito bites one member of the party. Wherever they are bit that part of their body starts to swell bigger than looks possible.",
    "Every surface in the room feels wet and slippery although none of them are wet or slippery.",
    "The party has a strong feeling that they are being followed, but they cannot find the one following them",
    "One member of the party must make a DC15 constitution save. On success they feel dizzy for 5 mins. On a fail they pass out for 5 mins",
    "There is a brief shimmer in the corner that almost looks like an invisibility spell",
    "The party sees a frog, but if they try to catch it, it jumps into the wall. The frog should re-appear around different corners",
]