random_occurances_list = [
    "One of the party members head starts to itch really badly",
    "One party member notices that their feet are really sweaty",
    "A random gold coin is found to be sitting on the floor of the current room",
    "There is a brown canvas sack in the corner of the room full of poop",
    "There is a ring that is tied to the ceiling with a note on it that says 'take me...please'",
    "There is some runic text in demonic that is scratched into the wall. It reads 'Helgar wuz Here'",
    "A fly buzzes past one of the party members face",
    "A stick figure is drawn on the wall of a guy with a sword. It looks really primitive",
    "The party hears a bolt of lightning strike outside reguardless of the current weather",
    "Have everyone roll a perception check. One person in the party smells something really yummy.",
    "One party memeber starts to sneeze uncontrollably",
    "There is a cat that is sitting in the corner of this room and is eyeing the party warily",
    "A large rat scuttles out of a hole, and grabs a grape and runs back in the hole",
    "There is a large pie sitting in the middle of the room",
    "A random potion is resting in the corner of the room",
    "Have everyone roll a perception check, one party member hears someone calling for help far away",
    "One wall has some writing on it that looks like it is written in blood... in demonic",
    "Have everyone roll a constitution save. The one who rolls the lowest has a shiver run down their spine",
    "Have everyone roll a wisdom save. The one who rolls the lowest forgets where they are for a second",
]