general_book_titles_list = [
"Gold, Lead and the Shapers of Reality: A Treatise on Alchemy",
"Fire, Oil and Steel : The Ways of the Forge and Smith",
"Ally's Journey to the Magic Castle, a children's tale of adventure",
"The Properties of Inverse Spell Formulary and its Effect on Transmutive Magic",
"The Tale of the Fifth Sister, an epic and allegorical high adventure story of redemption",
"Bellinoch's Guide to the Wilds of the Fey",
"Under the Storied Moon, a love story between a bard and werewolf",
"Untraceable Poisons and Their Alternative Uses",
"The Songs of the Warbling Dragon, a book of absolutely terrible sonnets",
"Under the Mountain: A Comprehensive History of the Dwarves",
"Why Are Goblins Green?, a cautionary children's tale",
"The Ghost Hunter's Lexicon",
"Fireballs Unlimited: Make a Big Bang and Become the Talk of the Town",
"The 10,000 Essential Prophecies of Rupert the Tiny",
"Social Uses of Necromancy: Why Find Friends When You Can Make Them?",
"Ungrid Ironhand's Complete Guide to Arms and Armor",
"The Telemetry and Physical Constraints of Intraplanar Instantaneous Transmission",
"Why Warlocks? A Deep Dive Into Those Who Bind Their Souls",
"Blips, Clicks and Hums: Nero Slipworthy's Beginner's Guide to Clockwork Construction",
"Not Today, a satirical book written as a guide for the lazy bard ",
"No Bones About It: The Bones Know, Understanding the Future Through Osteomancy",
"Are You There, Xorlack? It's Me, You: Empathic Connections With Extraplanar Beings",
"Bang, Zap and Schwing: An Explosive Guide to Evocation",
"The Owlbear and the Satyr, a feel good story of a garrulous fey and his favorite pet",
"Knives in the Knight, a gripping tale of betrayal, redemption and stabbing through heavy armor",
"Is the Astral Sea for Me?: A Travel Guide for the 53-54 Suicidally Adventurous",
"The Things You Never Wanted to Know: A History of the World's Worst Moments",
"Secret Places of the Ancient Arcanists",
"Secrets of Secret Cults: A Revealing Look At What They Don't Want You To Know",
"The Cart After the Horse: A Guide to Advancements in Autonomous Wagons",
"Gaffs & Gags: How to Use Cantrips in Practical Jokes",
"Angelicus Totalis: A Personal Journal of Journeys Through the Heavens",
"Gitrug and Clarg: Brothers to the End, a harrowing biography of an orc and his adopted goblin brother",
"Never Do What I Did: Billingsly Nertfarthing's Guide to Teleportation",
"Mishaps Fire and Ice: A Comparative Treatise on Evocative Spell Construction",
"Demigods and Avatars: How to Rise to the Top in Three Easy Steps, which seems like a pyramid  scheme",
"A Dark Guide to Forbidden Love Potions",
"The End of All Things: An Examination Into How the Wish Spell is Going to Destroy the Universe",
"That's a Big Nope: Murkat Gobstoppas Guide to Poisonous Insects",
"Of Gods and Celestial Beings: Are They Really There or Just a Myth?",
"All You Will Ever Need To Learn About Taverns, Ales and Alcohols, a seminal work by J. Majors",
"Controlling the Outcome Through Enchantment and Illusion: A Guide to Clouding the Mind",
"Librum Arcanum Geographica, an atlas of ley lines and magically significant locations",
"Boogeymen and Other Mythical Terrors: From Baba Yaga to the Jabberwock of the Talion Plains",
"An Alliance of Fools, a fictional work of politicalvintrigue that seems to closely mirror the present",
"Rain of the Heavens: The Day the Angels Fell",
"Marl's Penultimate Cookbook: From Cabbage Soup to Duck a l'Orange, Tavern Floor to King's Table",
"Prolific Cloners or Immortal Beings: The Truth About Elves Revealed",
"The Book: Inside Are All the Answers, a 400-page tome whose pages are completely empty",
]