general_evil_book_titles_list = [
	"How to put the FUN in funeral!",
	"How to torture your enemies the RIGHT way",
	"General imprisonment and you",
	"The bones of you enemies and broth (cook book)",
	"Splat",
	"Traps tresure and torture",
	"How to motivate minions",
	"Drangons, Darkness and Dungons",
	"Mein Kampf",
	"Dont let villan define YOU",
	"Effective and efficent ways to remove eyeballs",
	"Arch-nemmisis and other important people in your life",
	"Follow your nightmares, no matter where they lead",
	"Demotivational Calendar 221",
	"Smoking humans, where to put the spit",
	"Goblins, Goloush and greens",
	"How to get ogres on your side",
	"Necromance and Romance, Who says love has to die?",
	"The UN-holy bible",
	"The book of MORE-MEN",
	"How to convince others you arent TRULY evil",
	"Are you gonna finish that? Using ALL parts of humans in food",
	"Tigers and Lions and Bears, oh my! How to encourage beasts to stay in dungons",
	"How to win friends and influce dark eldrich beings",
	]