underdark_carrying_list = [
  "carrying underdark",
  "15cp, 2sp; a shirt of chainmail",
  "40cp, 10gp; a lockpicking kit",
  "50cp, 5sp; a luxurious cloak",
  "5sp, 2gp; an emerald ring",
  "34cp; a bottle of liquor",
  "10cp, 4sp; a healing potion",
  "20cp; a pair of brass knuckles",
  "15cp, 3sp; a ball of string",
  "4cp; a bundle of bread and cheese; a dagger",
  "Soiled rags; an old war medal",
  "2sp, 5gp; a swordfish",
  "20cp, 1pp; a book of sketches",
  "1cp, 10sp; an empty knapsack",
  "5gp, 2pp; a book on dwarven etiquette",
  "30cp; a pair of boots; a map of secret tunnels",
  "20cp, 5sp; a love letter from their sister-in-law",
  "30cp, 2sp, 3gp; a prayer idol",
  "17cp, 10sp; acceptance letter from the Academy of Scholars",
  "20cp; a whetstone",
  "5gp; two disguise kits",
  "10cp, 6sp; and assortment of cave fruit",
  "3cp; expensive and muddy purple robes",
  "12cp; 4sp; chewing tobacco; +1 hand wraps",
  "23sp, 58gp; potion of heroism",
  "3cp; 7gp; flaking bark bits; a potion of healing",
  "2cp, 42sp, 98gp; a solid gold puzzle box in the shape of a pyramid; a deck of rare playing cards",
  "9cp, 2sp; a pseudodragon; a (potentially) real treasure map",
  "5cp, 8sp; 8 throwing knives; a jade carving of a toad",
  "43cp, 64sp; an ox cart; 100gp worth of organic vegetables",
  "3cp, 5sp; a royalty statement for 34gp; 3 manuscripts",
  "4cp, 78gp; a pitch for square wheels; a 5 year plan",
  "1cp; a massive jug of guano",
  "18cp, 9sp, 2gp; a romance novel titled In the Enemy's Embrace",
  "34cp, 7gp; 3 vials of alchemist's fire; a token of feather fall",
  "469gp, 86pp; a diary written in stream of consciousness and spanning 430 years",
  "23cp, 5sp, 290gp a drafted business application; a bottle of gin",
  "59sp, 81gp; several vials of viscous liquids; a large needle",
  "3cp, 7sp; a large collection of rare tea leaves, a cast iron tea pot",
  "5cp, 8gp; a book titled Crystal Reading for Dummies; a large crystal ball worth 990gp",
  "2sp, 6gp; the spring fashion catalogue for 'Cavernguy'",
  "12sp, 14gp; a +1 dagger; bag of live insects for snacking",
  "8cp, 11sp; a dream journal filed with wild visions",
  "12sp, 13gp; a blank piece of parchment that when heated reveals a curious map of the underworld with an 'X' on it",
  "2gp, 4pp; a short sword; silver dragon head pendant on a short chain worth 120gp",
  "32gp; 6 tattoo needles; 4 bottles of ink; curved dagger",
  "14sp, 16gp; mushroom-based incense that stops pain when inhaled (6 uses good for 8 hours each)",
  "32cp, 6sp; steel waking stick/spear (1d8 piercing)",
  "16gp; mechanical drawings; a map of an underground lake; and underwater breathing apparatus",
  "14sp, 18gp; a ritual dagger; two empty vials",
  "2sp, 4gp; full wineskin; a charcoal sketch of their former self",
  "12sp, 22gp; 2 rings worth 50gp each; several fine silk handkerchiefs",
  "10sp, 11gp; a jar of wax, flint and steel",
  "22sp, 10gp; a box of two dozen matching rings worth 18gp; a tie-dyed stole",
  "10sp; necklace with cheap bronze medallion; dagger hilt with no blade",
  "21sp, 12gp; dagger hidden in boot (1d4 slashing damage)",
  "17sp, 4gp; brass knuckles; small pencil; journal inscribed with poems",
  "5sp, 8gp; bag stuffed with a cloak of invisibility",
  "12sp, 38gp; salve that conveys fire resistance (2 uses)",
  "38sp, 40gp; large pouch; small dagger",
  "35cp, 20sp; a tattered book titled Rare Bats of the World; a broken holy symbol" #this is the end of the NPC book
]

general_carrying_list = [
  "carrying general",
  "14cp,5sp,2gp; Belt-knife; scythe; bundle of wheat",                 #This is the beginning of the random encounters book
  "Empty Money pouch; a silver broach in the shape of a rabbit",
  "8cp, 1sp; Small bag of butterfly wings; pouch of herbs and a pipe",
  "15cp, 1gp;a novel titled Through the Weave; One packet of beans",
  "Nothing and proud of it",
  "17cp, 2sp; A wooden cup they carved themselves",
  "73cp painted to look like 73pp; a small jar of platinum paint",
  "32cp, 13sp; a hoop and a stick",
  "15sp; a necklace that contains a ball of yak hair",
  "21cp, 2sp, 3gp; an incredibly smooth rock they enjoy tumbling",
  "3sp, 8gp; a jar full of beef tallow; a crude map of the region",
  "5cp, 9sp, 1gp' a vial of wyvern poison",
  "4cp, 16sp; an oversized lollipop; a deck of cards",
  "6cp, 8sp, 12gp; Loaded dice; a directory of local gambling halls",
  "9cp, 2sp; knitting needles and a half finished scarf",
  "7cp; a large leather hat; a set of thieves' tools",
  "6sp, 1gp; a cup and ball game; trout in butcher paper",
  "4cp, 3sp, 1gp; a book about blacksmithing",
  "85cp; a note that says, \"Be careful, I love you. -Mum\"",
  "64sp; 12gp in loose gems; a rock-hammer",
  "14cp, 17cp, 4gp; a magnifying glass",
  "10sp,; brewer's kit and waterskin of whiskey",
  "32cp; a collection of dolls that look like the party",
  "A whistle only a badger named Jenny can hear",
  "5cp, 30sp, 9gp; a very small hat",
  "19cp, 2sp; a spyglass that can suck out an eyeball on command",
  "14cp, 92sp; and error filled map of the realm",
  "A cursed pen knife (Look at curse table encounters book page 248)",
  "32cp, 7sp, 3gp; A pair of shoes in need of resoling",
  "8cp; and IOU that reads \"Owe you three sacks of wool. Hamm\"",
  "94cp, 1gp; A mask that hides their face and a hit list of local thugs",
  "7cp, 8sp, 2gp; A dark artifact (could be a corrupted artifact)",
  "34cp, 10sp; a broken lute; a crumpled love letter",
  "3cp, 5sp, 7gp; a sack of dates; a pound of dried apricots; a fishing pole",
  "4cp, 6sp; a set of wooden teeth",
  "7cp, 92sp; a bottle of baby tears they want to sell",
  "9cp, 53sp, 900gp; A dark leather tome titled How to Act Human",
  "5cp, 5sp, 5gp; five rings worth 55gp",
  "3cp, 81sp; Joiner's tools; a blood-soaked rag",
  "32cp, 5sp, 1pp; a crust of moldy bread; some salted pork",
  "45cp, 2sp; and undead hand that is very important to them",
  "61cp, 3sp; a forgers kit; a lost of nobles names",
  "92cp, 3gp; cufflinks that conceal to doses of Drow poison",
  "52cp; a sack of fingernails (each more precious than the last)",
  "89cp, 3sp; a belt buckle with a hidden lock-pick",
  "62cp, 32sp; a diamond that appears to be worth 500gp (its not)",
  "25cp, 6sp, 24gp; a sport, the first of its kind",
  "6cp, 2gp; A sandwich made of nut butter and smashed jam",
  "21cp, 5sp; an exquisite dagger carved from the bones of a dragon born",
  "4cp, 74sp; a wineskin willed with a potion of haste",
  "8cp,53sp; a fake beard; a tome filled with gift ideas for hundreds of children",
  "91sp; A recipe for pot pie; a small sack of peas; spices;",
  "3cp 14sp; A jar of honey; A box containing a large queen bee",
  "7cp, 13sp; a gate spell scroll",
  "A pocket sized copy of the realm's founding documents",
  "A frog (roll a d6, on a 1, it was once a prince)",
  "31cp; a rudimentary coloring book; some colored wax pieces",
  "4cp, 3sp, 2gp; A set of woodworker's tools",
  "8sp, A minor gem worth 1gp",
  "5gp; a +1 scimitar engraved with the name \"Trevor\"",
  "42sp; A tub of grease; a wand of webs",
  "55gp; a vial of de-aging serum that takes 20 years of a creatures life",
  "8sp, 4gp; a tophat concealing a dozen squirrels",
  "3sp; a bottle of milk; an ornate quarterstaff",
  "And unopened letter challenging them to a duel with a merchant",
  "15cp; a jar capable of storing memories",
  "8cp; a vial labelled \"DO NOT OPEN\" that contians the expelled gas of a king",
  "90sp; a liniment that helps with insomnia",
  "13cp; directions to a guard's house; a box of juice",
  "Sheet music from a bard you've never heard of; a -1 charisma pinky ring",
  "13pp; a jar of beard oil that is also flammable",
  "29sp; a small painting of an elven girl",
  "35cp; a colorful piece of chewing taffy that never loses its flavor",
  "A list of several gods with at least nine crossed out",
  "14 vials of a potion that smells great, but does nothing",
  "a watch chain; a pair of fancy hair combs",
  "a note with the location of a dragon's lair",
  "30sp; A pair of bi-leansed readers; a sack of candies",
  "a mourning ring featuring the eye of their mother",
  "1cp, 1sp, 1gp, 1pp; a deck of many things",
  "390gp; a sack of grave dirt; a spade; a beret",
  "42cp, 71sp,; 3 vials of a tonic that adds +2 to strength for an hour",
  "62cp, 21sp, 92gp; a gag and hood; 2 vials of purple worm poison",
  "3cp, 9sp, 21gp; and opal carved in the shape of a jawbone",
  "5cp; a sport's almanac",
  "92sp; Manticore bait; a griffon call; sacks of meat",
  "a 20% coupon for mage you look (Random encounters book pg 128)",
  "18cp, 4sp; a stuffed tiger; a tuna sandwich",
  "3cp; a speckled egg; a broken music box;",
  "92gp; a small heart in a smaller cage;",
  "3gp; a bag of salt; a bag of pepper; a bag of octopus tentacles",
  "a lyre that's missing all but one string",
  "a glass orb; a raven's beak; a vial of tiger blood",
  "5cp; a lump of coal; a small box filled with ashes",
  "52sp; an herbalist's kit; a neatly folded poster with their face on it",
  "5,256gp; a notebook listing all the things they've done this year",
  "13sp, 2gp; a few gnarled balls of thick cord and cloth",
  "81cp, 3sp; a list of rules for something called \"Brawl Joint\"",
  "Ink that disappears but can be revealed with a little heat",
  "a 32-page booklet of so-called \"haters\" with a few names crossed off" #This is the end of the random encounters book
]

outskirts_carrying_list = [
  "carrying outskirts",
  "3sp, 9gp' tinker's tools; 20lbs of scrap",    #This is the begining of NPC Outskirts
  "3cp, 13sp, 33gp; a +1 rapier, a personal writ to allow cross jurisdictional arrests",
  "12cp, 87gp; a device that can detect ghosts within 120ft; a book of horror tales",
  "2cp, 7gp; a bag of black clothes and a toothbrush",
  "15sp, 9gp; 3 potion of hill giant strength",
  "2cp; 2 canisters of lantern oil; flint and steel",
  "6sp, 4gp; a needle and thread; a religious symbol featuring a sewn mouth",
  "12sp, 96gp; a red umbrella ; a jar of silver butterflies",
  "22cp, 3gp; a nugget of gold worth 340gp",
  "23gp, 42pp; 25--gp worth of rare poisons and venoms in glass vials",
  "12cp, 3sp, 17gp; a piece of ripped cloth; wolf treats",
  "4cp; a half-finished study on the territorial nature of the yeti; a backpack of camping supplies",
  "2sp",
  "12cp, 3sp; a pie; a crook; 44 sheep",
  "43cp, 77sp, 2500pp, all in a demiplane they can access with a wristflick; a spellbook and robes",
  "1cp, 12sp; one jerky ration",
  "367gp, 88pp; priceless fur coat; 3 bear traps",
  "6cp, 3sp, 8gp; a set of cursed panpipes",
  "2cp, 5sp",
  "23sp, 286gp; 3 second-hand horses and carts",
  "41sp, 12gp; a half-eaten pastry; a hat with a feather in it; an earhorn",
  "2sp; a horse blanket; a saddle",
  "9sp, 1gp; a bucket; a rudimentary sketch of a giant joust",
  "12gp, 6sp; a map of prison; a set of thieves' tools",
  "22cp, 4sp; a small pouch of catnip; basic spell components",
  "44sp, 18gp; 4 vials of poison, a large hammer",
  "31sp, 2gp; cartographer's tools; a small bag of ginkgo biloba",
  "6sp, 44gp; 4 red candles; an ancient grimoire in an unknown language",
  "12cp, 6sp; a hand mirror; a brush; an ivory hair comb",
  "4sp, 4gp; a broken shortsword; a +2 dagger",
  "9sp; a dagger; a holy symbol; a small bowl with dried blood in the bottom",
  "6sp; a fake mustache and beard; a forged letter of safe passage",
  "11sp, 7gp; a full wineskin; a small bag of wild onions for snacking",
  "14gp; leather apron; a cursed +1 knife",
  "a bottle of ale; a map of nearby territory; a personal journal",
  "32gp; a bottle of perfume; a comb; a jar of pomade; a scroll",
  "2gp, 17sp; a skin of milk; a pouch of weeds; a dagger",
  "11sp, 7gp; a spyglass, a map of the coast",
  "13sp, 24gp; a silver key; a small box of candy; an Elemental Gem",
  "22sp, 2gp; a small portrait; several oft-read love letters",
  "11sp, 5gp; a box of fish hooks, a tiny scalpel",
  "13sp, 9gp; a human femur fashioned into a crude machete",
  "5sp, 15gp; a notebook ; a quill a small jar of poisonous ink",
  "3sp, 23gp; a tuning fork; a lute; crumpled sheet music",
  "11sp, 6pgp; an amber amulet; a caramel candy; a ransome note written in foul-smelling green ink",
  "7sp, 29gp; gold earrings worth 500gp; a cracked mirror",
  "10sp; 30gp; a wheel of camembert that emits a faint glow",
  "38gp; a string of crystal beads; a stained burial shroud embroidered with gold thread",
  "4sp, 19gp; a white jade medallion; an ancient longsword",
  "7sp, 5gp; a bow and arrow; a small jar of ointment",
  "3 bags of brine shrimp laced with a deadly toxin",
  "4gp; an orcish ritual knife",
  "2sp, 7gp; a detailed description of a nearby house",
  "3gp; a corncob pipe; a rusty luck blade",
  "49gp; a dark mace; a prism that dosen't refract light",
  "34pp; an unsigned deed to a parcel of land worth 175,000gp; a grudge against their father",
  "22cp; a mouse that can do a time step; a full keyring; a small spoon",
  "30cp, 9sp; a ring of spell storing; a +1 rod of the pact keeper",
  "42gp; a call lightning spell scroll; a necklace made of crocodile teeth",
  "52cp; a hag's eye; a small box of sweets; a child's thumb" #This is ending NPC Outskirts
]

small_town_carrying_list = [
  "carrying small town",
  "13cp, 4sp; a cmall knife; a horn made of bone",   #This starts NPC small town
  "7sp; a jar of honey; a few stale biscuits",
  "7sp, 9gp; an expired letter of marque; a spyglass",
  "6cp; a play they wrote and will definitely get produced one day",
  "4cp, 14sp; a wooden fork; a pound of smoked fish; a large piece of cardboard",
  "9gp; a very loud hen named Eggy",
  "20cp, 4sp; a needle and thread; a bottle of good wine",
  "21cp, 9sp, 2gp; a red cap with a fish embroidered on the side",
  "3gp, 2pp; a set of fish hooks; two spears; a bucket of chum; a written will",
  "a set of dominos; a small vial of poison; 4 strips of beef jerky",
  "2sp, 9gp; a bottle of holy water; the skull of a pigeon",
  "8cp; an extra pair of shoes; a deck of cards with 5 aces",
  "23cp, 2sp; an ear horn; a necklace made of small bones",
  "9cp, 10sp; an incomplete sketch of their deitey; four meat pies",
  "6cp, 9sp; a knife carved from bone; 6 darts; a bottle of ale",
  "4cp; a tiny leather bag of magic teeth",
  "4gp; a quill pen; some leather straps; six needles covered in black resin",
  "6sp; a sack of marbles ; a coby of a king's decree",
  "22cp; a bedroll; a bag of small dead lizards; a flyswatter",
  "6gp; a basket of peaches, one of which is rotten",
  "1cp, 19sp; a set of artist's tools; some sketch paper; a talisam they don't know about in their boot",
  "21cp; a jagged knife; a holy symbol; two bags of kindling",
  "7gp; a small metal box whose lock cannot be picked",
  "33cp; a wineskin; a bag with a hole in it",
  "804cp; individually wrapped slices of cheese; a half full wine-skin",
  "12cp, 43sp; 2 halves of a broken flute",
  "5sp; a hair pin, a small ivory radish worth 35gp",
  "3gp; a sizable amount of pocket lint that is actually violet fungus",
  "0cp, 1sp, 13gp; a bag of parched corn; a pork chop wrapped in waxed paper",
  "9gp; a fox brooch worth 70gp; a sack of candies",
  "9gp; a pair of undergarments that do not belong to them",
  "92sp; razor-sharp knife; a homemade bar of soap; a list of known irritants",
  "32sp; a small canary; a bag of beans; a lute",
  "8cp; a bundle of rabbit skins; a bag of wild onions; a sling with 4 stones",
  "20gp; a long pipe; a pouch of aromatic tobacco",
  "5cp, 9sp; a dirty handkerchief; a map written in an unknown tongue; a sextant",
  "a magnetized piece of iron; flint and steel",
  "plans for a roadside attack on a caravan",
  "4cp; a silver ring worth 4gp; a whistle that makes no sound (30 percent chance of attracting 2d4 wolves",
  "10gp; a large wineskin; a full snuff box; a wanted poster",
  "12sp; a bag of holding; 1d10 bones and 2d4 organs",
  "51sp, 5gp; a black pointy hat; earings of ivory",
  "23cp; two infant children",
  "22cp, 2gp; a cat in a carboard box (there is a 20 percent chance the cat is fiendish)",
  "6cp, 22sp; a portable cutting board",
  "23cp, 83gp; an invoice from a noble; a blet with sacks of differnt types of flour",
  "31cp, 1gp; a button; a wooden token; a stone that unlocks a warded tomb; a fishbone knife; a lich's phylactery; an emerald eye; a snake egg; a paralyzed pixie",
  "3sp, 154gp; a rusty key; a minor flamethrowing device",
  "12cp, 8gp; a set of panpipes; a pair of manacles; a lock pick",
  "23cp; a fan made from rare bird feathers worth 600gp that acts as an arcance focus",
  "45cp; a fishing rod of exceptional quality; a letter detailing \"the incident\"",
  "32cp; a crudely scrawled list of phrases in Common",
  "84cp; a heavy-duty cast iron frying pan; some suspicious mushrooms",
  "3cp; a magic sword worth at least 3000gp",
  "88sp, 3gp; an amateur map into the mountains with an X marking a well devised trap",
  "10cp; a baguette and some stinky cheese",
  "32sp, 9gp; forged invitations to a nobleman's masquerade",
  "4pp; a gandy haversack whose contents are worth 745gp",
  "21cp, 30gp, 18pp; an assassin's guild seal; a contract detailing a nobles's description",
  "a pouch of soggy herbs"      #This is the end of NPC small town
]


carrying_lists = [general_carrying_list, small_town_carrying_list, outskirts_carrying_list, underdark_carrying_list]