underdark_description_list = [
    "description underdark",
    "with a pockmarked face and a scraggly beard.",             #First entry in the NPC book
    "with breath reeking of onions but with a winning smile",
    "with the finest clothes and clearly in a hurry",
    "with a face caked in makeup and muscular arms",
    "with a handsome face except for a giant boil on their nose",
    "cover head to toe in plate armor",
    "with a broken nose and missing teeth",
    "with a patchy beard and a finger in their nose",
    "with a face covered in piercings and a mouth full of gold teeth",
    "with a missing eye and leg",
    "who is 5 feet tall and thin as a rail",
    "who is heavy in the torso yet light on their toes",
    "as bald and beardless as a baby",
    "wearing a fancy ballgown and expensive jewlery",
    "with scabs all over their body",
    "with food-stain covered clothes",
    "with small stature and a nervous demeanor",
    "with heavy eyelids and a constant yawn",
    "with shaggy red hair and a giant mole on their cheek",
    "with a hook for a hand and wearing an over-sized hat",
    "with pale white eyes and large black ears",
    "with their nose turned to the sky and wearing a purple robe",
    "with a sly grin chewing tobacco",
    "with menacing black plate armor",
    "who shuffles along slowly, their body covered in bark",
    "with wild hair and leather pants",
    "with high green pigtails and a pseudodragon perched on their shoulder",
    "with a bright orange jumpsuit and several knives in their belt",
    "with an ox sled of fresh food and wearing a wide brimmed hat",
    "with a pink crop top wielding twin short swords",
    "with a leather apron and an ironworker's mask",
    "with ragged clothes and some fabric scraps shoved up their nose",
    "with popping veins and a mouth frothing with excitement",
    "with open robes and angular face paint",
    "with eager eyes and silver hair",
    "with blue hair and a kindly attitude",
    "with immaculate white robes and a monocle",
    "with a plump figure and serene attitude",
    "staring intently at a large crystal ball they are carrying",
    "with effortlessly mussed hair and a photogenic face",
    "with sharp features, dark hair, and a ragged black cloak",
    "with a shaven head, odd green scales on their neck, nad a curious fishy odor",
    "with a long red beard thrown over their shoulder and deep-set black eyes",
    "with a long white mohawk, sparkling blue eyes, and toned physique",
    "with arcane tattoos over every visible surface of their body",
    "with a squat body, close cropped hair and large rat perched on their shoulder",
    "with ragged clothes, blind eyes, and a steel walking stick sharpened to a lethal point",
    "with a bald head, black beard and the longest fingernails you've ever seen",
    "with dark skin, long, sleek blue hair and matching spiral tattoos on both sides of their neck",
    "with bulging watery eyes, large webbed hands, and a humped back",
    "with fine dress, regal bearing and an entitled attitude",
    "with short dark hair, an impressively curled mustache and teeth filed to points",
    "with curly brown hair, travelers garb and a patch over one eye",
    "with tattered white robe, long white hair and missing one arm",
    "with wrinkled face, deep set eyes, blackened and pitted teeth and noxious breath",
    "with a large broken nose, gallon-sized fists and wiry gray hair",
    "with expressive eyebrows, a lilting voice and several nose, lip and ear piercings",
    "with bow legs and a thick middle reg hair and a bushy beard",
    "with an easy smile, friendly attitude and terribly sarcastic demeanor",
    "riddled with scabs and small cuts"                     #Last entry in the NPC book
]

general_description_list = [
    "description general",
    "with shaggy hair and a slight overbite",                #First entry in the Random encounters book
    "with deep set eyes and an upturned nose",
    "with a wide smile and a fashionable mole",
    "with a steady gaze and pursed lips",
    "with a deep facial scar and a gruff exterior",
    "with a pug nose and lots of freckles",
    "with a round face and rosy cheeks",
    "with a few hairs springing out of a wart on their face",
    "with a heavy limp and a can do attitude",
    "with a kind face and a slow drawl",
    "with shifting eyes and a hushed voice",
    "with a few missing teeth and a hungry gaze",
    "with a massive nose and a tight mouth",
    "with hooded eyes and a casual tone",
    "with wild hair and a seating brow",
    "with oily skin and whistling nostrils",
    "with large ears and an oval face",
    "with a strong jaw and a hearty laugh",
    "with a slack jaw and a tendency to mouth breathe",
    "with a gat toothed grin and grey eyes",
    "with a pot belly and an infectious giggle",
    "with a blank expression and wild ear hair",
    "with a face full of piercings",
    "with more tattoos than un-inked skin",
    "with buns of steel and armor to match",
    "with scabby knuckles that won't stop cracking",
    "with a sick papadour haircut",
    "wearing the corset of a slimmer person",
    "with a slack face on one side impeding their speech",
    "with a tongue seemingly too big for their mouth",
    "with a posh attitude and clothes to match",
    "with a dour expression",
    "with the biggest head of all time",
    "with broad shoulders and a low cut tunic",
    "with a hunched back and sores",
    "with friendly eyes and the grace of a dancer",
    "devoid of eyebrows and a sense of humor",
    "with a soot covered face",
    "with a dnet in their skill that's healed over",
    "in a purple tunic, ascot and patent leather boots",
    "covered in black tar and white feathers",
    "with a broken arrow stuck in the side of their head",
    "with black eyes that lack irises",
    "face buried in a book about geese",
    "holding a tiny dog and fighting back tears",
    "humming to themselves and scratching flaky skin",
    "with a narrow face and fine, almost too perfect features",
    "with a bruised eye and a busted lip",
    "with a lumpy nose that looks a bit infected",
    "with a beehive hairdo that makes them seem taller",
    "has a neck twice as wide as their face",
    "has a face that appears stitched together",
    "looks like they're about to vomit",
    "is dripping in sweat",
    "is expertly juggling a trio of daggers",
    "has a drippy nose and red cheeks",
    "is wearing clothes that are three sizes too big",
    "looks twice their age",
    "with a pretty face and big ideas",
    "wearing goggles and chomping a smoldering cigar",
    "with the energy of an overstimulated child",
    "wit bangs that everyone agrees do not suit their face",
    "nervously chewing their upper lip",
    "blind, but making it work",
    "still sporting the scars from a rogue owlbear attack",
    "has one of those faces",
    "with a chin that could block out the sun",
    "with a whisper-quiet voice",
    "with a cute smile and a belt of knives",
    "wearing far too many belts and silver jewelry",
    "with the biggest, bushiest beard",
    "is blessed with lavish curves",
    "is a scythe-wielding farmer",
    "with armor that shines like the sun",
    "with an almost hypnotic voice and air of importance",
    "who looks like they just woke up",
    "in a tight-fitting red-scaled jacket",
    "wearing temple robes and a surprised expression",
    "with greasy hair and hands to match",
    "with a hard weathered face",
    "walks with the grace of a dancer",
    "wearing a crop top to show off their impressive abs",
    "in black leather and a pair of sharp heeled boots",
    "has a permanent squint and a stiff upper lip",
    "who appears as if they were struck by lightning",
    "with a smile that is all teeth and no joy",
    "with flashy pink hair",
    "with a smell that is off-putting",
    "has bloody, nail free fingertips",
    "in a droopy robe",
    "in a hat that is as tall as they are",
    "with no arms, but two mage hands",
    "with bare feet and freckled cheeks",
    "dressed in a patchwork coat of dozens of fabrics",
    "with one leg, and a hangman's scar on their neck",
    "is deaf and uses gestures to communicate",
    "has shaggy hair, baggy clothes and a chill attitude",
    "has cheekbones that could cut glass and eyes to match",
    "wearing a hood that covers their gaunt face",
    "with a handsome face and sure, kind smile"              #End of the random encounters book
]
outskirts_description_list = [
    "description outskirts",
    "with a rusty metal contraption for arms and legs",         #Start of NPC Outskirts
    "dressed in a military uniform decorated with many medals",
    "carrying all manner of strange and somewhat sinister apparatus",
    "with an undercut and piercings",
    "who is a teensy tiny person",
    "frothing at the mouth and carrying a flaming torch",
    "with serene eyes and a mouth that has been sewn shut",
    "with fine cheekbones, dark hair tied in a messy ponytail and red robes",
    "with gold plated teeth and a winning smile",
    "with a white lab coat and various glass jars",
    "with a shaggy appearance and two pet wolves",
    "with a bright young face and large backpack",
    "with a thin silhouette and who rattles each time they take a step",
    "with a shepherds crook and a flock of sheep",
    "incredibly elderly and wearing thin framed glasses",
    "with sharpened teeth and hollow eyes",
    "with icy blue eyes and a large fur coat",
    "with a flat top haircut and a heavy dose of cologne",
    "with dreadlocks, socks, and sandals and a chill attitude",
    "with slicked-back hair and a slimy attitude",
    "with perfectly coiffed brown hair and a striking underbite",
    "with a bad case of bowlegs",
    "with a heavenly voice and pinchable cheeks",
    "with long white hair, an anxious manner and a pronounced limp",
    "with a tear-streaked face and short spikey hair",
    "with broad shoulders, strong hands and a patch across one eye",
    "with a wide smile and meancholy eyes",
    "with lank black hair, yellowed teeth and horrible breath",
    "with long auburn hair and sparkling golden eyes",
    "with bright red hair and a chain mail shirt that hangs down to their knees",
    "with short brown hair and priestly robes",
    "with perfectly trimmed hair, clean new clothes and an elegant walking stick",
    "with savage body odor and an exceptionally nice haircut",
    "with a tatoo of a spider in the middle of their forehead",
    "without the ability to finish a sentence",
    "with an unusually high end sense of fashion",
    "with multiple facial piercings and wearing a bright blue sari",
    "with wavy brown hair, soft leather breeches and a peg leg",
    "with a large floppy hat and face concealing scarf",
    "with a lavender gown and matching eyes",
    "with bloodshot eyes and an upper lip that looks permanently upturned",
    "with a rectangular head and a fox tail necktie",
    "with light blue robes, steady hands and blonde bangs that hide their eyes",
    "with an enviable tan and arms covered in blue tribal tattoos",
    "with a silver hooded gown and smiling eyes",
    "with flowing hair, gold earrings and prominent cheekbones",
    "with a checkered vest, bulging eyes and a thunderous laugh",
    "with a grey cloak covering a bony frame",
    "with a badly burned body that appears to be held together with wire",
    "who is missing an eye and is covered in bruises and scrapes",
    "wearing a crown made of seashells",
    "in a dress woven from caterpillar silk",
    "with a thousand yard stare and an iorn grip on their dagger",
    "in a set of dock worker's clothes that are covered in bog mud",
    "wearing armor crafted from the bones of their foes",
    "with flowing straw colored hair and flanked by a company of pike-wielding paladins",
    "missing one cheek but covering the wound with a piece of plaster",
    "a towering figure carrying a heavy lantern",
    "heavyset gold dragonborn in ill-fitting clothes",
    "wearing all black save for a white orchid pinned to their left breast" #End of NPC outskirts
]

small_town_description_list = [
    "description small town",
    "with a colorful dress, bright eyes and a ragged scar across the temple",    #Start of NPC small town
    "with dark skin and bright yellow eyes",
    "with a waxed mustache and milky left eye",
    "with fair skin and pageboy haircut",
    "with a stocky build and a permanent smirk",
    "with elaborate white facial hair and wrinkled skin",
    "with wild shaggy hair and a crazed look in their eyes",
    "with long, tangled hair and teeth filed to points",
    "with a leather vest and short, curly brown hair",
    "with a bald head and numerous gold earings",
    "with a blue mohawk and a ring in their nose",
    "with a missing hand and an angry stare",
    "with curly holden hair and a skip in their step",
    "with close-cropped gray hair and a humble demeanor",
    "with a fierce countenance and wild corona of hair",
    "with hooded eyes and restless hands",
    "with all black clothes and an expression of madness",
    "with a golden eyebrow ring and a smart blue vestment",
    "with a patch over one eye and a long pipe drooping from their mouth",
    "with firey eyes and a small, pouty mouth",
    "with strong arms and a silver tounge",
    "with short black hair and a worn leather jerkin",
    "with lard-slicked hair and mud-encrusted hands",
    "with a whisper-like voice and a record-length beard",
    "with a ruddy complexion and a runny nose",
    "with a missing front tooth and badly burned hands",
    "with a prominent brow and crooked teeth",
    "with an elegant gait and fine clothing",
    "with an attractive but dirty face and nine fingers",
    "with dainty ears and a pert nose",
    "with broad shoulders and a salty tongue",
    "with an easy grin and receding hairline",
    "with a long, elegant mustache and narrowed eyes",
    "with long black hair and tan leather breeches",
    "with one twitchy eye and a prominent lisp",
    "with dirty blond hair and pock-marked skin",
    "with one ragged ear and bright red hair",
    "with a highborne air and neatly trimmed whiskers",
    "with bushy grey hair and four wooden teeth",
    "with long white hair and a purposeful gait",
    "with a high-pitched voice and campy attitude",
    "with brown bangs and eyes stuck in a perminent roll",
    "with hands the size of dinner plates",
    "carrying a box that lets out an occasional meow",
    "with a leather apron and cleaver at their belt",
    "with a face covered in flour",
    "with silver buttons and precious stones sewn onto their clothing",
    "with an innocent expression and a snug white cardigan",
    "with a strong accent and a dominant chin",
    "with a bearkish face and an affinity for birds",
    "wearing large waterproof boots with a fishing rod over their shoulder",
    "in a dingey blue tunic and wearing a wig",
    "with a plump figure and heavy-duty apron",
    "with a woven bamboo hat that hides their eyes",
    "with watery eyes and a slimy disposetion",
    "dressed in colorful rags with bells on their shoes",
    "with a bust-worthy visage and a sparkle in their eye",
    "with impeccable posture and golden hair",
    "with sharp eyes and a ready longbow",
    "with algae-covered skin and a horrible cough"
]


description_lists = [general_description_list, small_town_description_list, outskirts_description_list, underdark_description_list]