description_list = ["with a pockmarked face and a scraggly beard.",             #First entry in the NPC book
                    "with breath reeking of onions but with a winning smile",
                    "with the finest clothes and clearly in a hurry",
                    "with a face caked in makeup and muscular arms",
                    "with a handsome face except for a giant boil on their nose",
                    "cover head to toe in plate armor",
                    "with a broken nose and missing teeth",
                    "with a patchy beard and a finger in their nose",
                    "with a face covered in piercings and a mouth full of gold teeth",
                    "with a missing eye and leg",
                    "who is 5 feet tall and thin as a rail",
                    "who is heavy in the torso yet light on their toes",
                    "as bald and beardless as a baby",
                    "wearing a fancy ballgown and expensive jewlery",
                    "with scabs all over their body",
                    "with food-stain covered clothes",
                    "with small stature and a nervous demeanor",
                    "with heavy eyelids and a constant yawn",
                    "with shaggy red hair and a giant mole on their cheek",
                    "with a hook for a hand and wearing an over-sized hat",
                    "with pale white eyes and large black ears",
                    "with their nose turned to the sky and wearing a purple robe",
                    "with a sly grin chewing tobacco",
                    "with menacing black plate armor",
                    "who shuffles along slowly, their body covered in bark",
                    "with wild hair and leather pants",
                    "with high green pigtails and a pseudodragon perched on their shoulder",
                    "with a bright orange jumpsuit and several knives in their belt",
                    "with an ox sled of fresh food and wearing a wide brimmed hat",
                    "with a pink crop top wielding twin short swords",
                    "with a leather apron and an ironworker's mask",
                    "with ragged clothes and some fabric scraps shoved up their nose",
                    "with popping veins and a mouth frothing with excitement",
                    "with open robes and angular face paint",
                    "with eager eyes and silver hair",
                    "with blue hair and a kindly attitude",
                    "with immaculate white robes and a monocle",
                    "with a plump figure and serene attitude",
                    "staring intently at a large crystal ball they are carrying",
                    "with effortlessly mussed hair and a photogenic face",
                    "with sharp features, dark hair, and a ragged black cloak",
                    "with a shaven head, odd green scales on their neck, nad a curious fishy odor",
                    "with a long red beard thrown over their shoulder and deep-set black eyes",
                    "with a long white mohawk, sparkling blue eyes, and toned physique",
                    "with arcane tattoos over every visible surface of their body",
                    "with a squat body, close cropped hair and large rat perched on their shoulder",
                    "with ragged clothes, blind eyes, and a steel walking stick sharpened to a lethal point",
                    "with a bald head, black beard and the longest fingernails you've ever seen",
                    "with dark skin, long, sleek blue hair and matching spiral tattoos on both sides of their neck",
                    "with bulging watery eyes, large webbed hands, and a humped back",
                    "with fine dress, regal bearing and an entitled attitude",
                    "with short dark hair, an impressively curled mustache and teeth filed to points",
                    "with curly brown hair, travelers garb and a patch over one eye",
                    "with tattered white robe, long white hair and missing one arm",
                    "with wrinkled face, deep set eyes, blackened and pitted teeth and noxious breath",
                    "with a large broken nose, gallon-sized fists and wiry gray hair",
                    "with expressive eyebrows, a lilting voice and several nose, lip and ear piercings",
                    "with bow legs and a thick middle reg hair and a bushy beard",
                    "with an easy smile, friendly attitude and terribly sarcastic demeanor",
                    "riddled with scabs and small cuts",                     #Last entry in the NPC book
                    "with shaggy hair and a slight overbite",                #First entry in the Random encounters book
                    "with deep set eyes and an upturned nose",
                    "with a wide smile and a fashionable mole",
                    "with a steady gaze and pursed lips",
                    "with a deep facial scar and a gruff exterior",
                    "with a pug nose and lots of freckles",
                    "with a round face and rosy cheeks",
                    "with a few hairs springing out of a wart on their face",
                    "with a heavy limp and a can do attitude",
                    "with a kind face and a slow drawl",
                    "with shifting eyes and a hushed voice",
                    "with a few missing teeth and a hungry gaze",
                    "with a massive nose and a tight mouth",
                    "with hooded eyes and a casual tone",
                    "with wild hair and a seating brow",
                    "with oily skin and whistling nostrils",
                    "with large ears and an oval face",
                    "with a strong jaw and a hearty laugh",
                    "with a slack jaw and a tendency to mouth breathe",
                    "with a gat toothed grin and grey eyes",
                    "with a pot belly and an infectious giggle",
                    "with a blank expression and wild ear hair",
                    "with a face full of piercings",
                    "with more tattoos than un-inked skin",
                    "with buns of steel and armor to match",
                    "with scabby knuckles that won't stop cracking",
                    "with a sick papadour haircut",
                    "wearing the corset of a slimmer person",
                    "with a slack face on one side impeding their speech",
                    "with a tongue seemingly too big for their mouth",
                    "with a posh attitude and clothes to match",
                    "with a dour expression",
                    "with the biggest head of all time",
                    "with broad shoulders and a low cut tunic",
                    "with a hunched back and sores",
                    "with friendly eyes and the grace of a dancer",
                    "devoid of eyebrows and a sense of humor",
                    "with a soot covered face",
                    "with a dnet in their skill that's healed over",
                    "in a purple tunic, ascot and patent leather boots",
                    "covered in black tar and white feathers",
                    "with a broken arrow stuck in the side of their head",
                    "with black eyes that lack irises",
                    "face buried in a book about geese",
                    "holding a tiny dog and fighting back tears",
                    "humming to themselves and scratching flaky skin",
                    "with a narrow face and fine, almost too perfect features",
                    "with a bruised eye and a busted lip",
                    "with a lumpy nose that looks a bit infected",
                    "with a beehive hairdo that makes them seem taller",
                    "has a neck twice as wide as their face",
                    "has a face that appears stitched together",
                    "looks like they're about to vomit",
                    "is dripping in sweat",
                    "is expertly juggling a trio of daggers",
                    "has a drippy nose and red cheeks",
                    "is wearing clothes that are three sizes too big",
                    "looks twice their age",
                    "with a pretty face and big ideas",
                    "wearing goggles and chomping a smoldering cigar",
                    "with the energy of an overstimulated child",
                    "wit bangs that everyone agrees do not suit their face",
                    "nervously chewing their upper lip",
                    "blind, but making it work",
                    "still sporting the scars from a rogue owlbear attack",
                    "has one of those faces",
                    "with a chin that could block out the sun",
                    "with a whisper-quiet voice",
                    "with a cute smile and a belt of knives",
                    "wearing far too many belts and silver jewelry",
                    "with the biggest, bushiest beard",
                    "is blessed with lavish curves",
                    "is a scythe-wielding farmer",
                    "with armor that shines like the sun",
                    "with an almost hypnotic voice and air of importance",
                    "who looks like they just woke up",
                    "in a tight-fitting red-scaled jacket",
                    "wearing temple robes and a surprised expression",
                    "with greasy hair and hands to match",
                    "with a hard weathered face",
                    "walks with the grace of a dancer",
                    "wearing a crop top to show off their impressive abs",
                    "in black leather and a pair of sharp heeled boots",
                    "has a permanent squint and a stiff upper lip",
                    "who appears as if they were struck by lightning",
                    "with a smile that is all teeth and no joy",
                    "with flashy pink hair",
                    "with a smell that is off-putting",
                    "has bloody, nail free fingertips",
                    "in a droopy robe",
                    "in a hat that is as tall as they are",
                    "with no arms, but two mage hands",
                    "with bare feet and freckled cheeks",
                    "dressed in a patchwork coat of dozens of fabrics",
                    "with one leg, and a hangman's scar on their neck",
                    "is deaf and uses gestures to communicate",
                    "has shaggy hair, baggy clothes and a chill attitude",
                    "has cheekbones that could cut glass and eyes to match",
                    "wearing a hood that covers their gaunt face",
                    "with a handsome face and sure, kind smile"              #End of the random encounters book
]