qwirk_list = [
    "A white scar across their eye",
    "An abnormally high voice",
    "An abnormally low voice",
    "A peg leg",
    "Two metal hooks for hands",
    "VERY expensive clothing",
    "A bracelet with the symbol of a (think of something cleaver here)",
    "A very expensive looking, glowing amulet with a large gemstone",
    "An inexplicable boston accent",
    "Hair that goes down to their knee caps",
    "A broken lute is strung across their back",
    "A signet ring with an odd symbol on it",
    "Large burn marks on the right side of their body",
    "Slightly cross eyed",
    "An extremely long nose",
    "Quite large feet",
    "A large mole on the side of their face",
    "Golden glasses",
    "Right arm is in a sling",
    "In a wheelchair",
    "Clothes has small flecks of blood all over",
    "Left hand is a dragon claw",
    "Eyes sparkle as they reflect the light",
    "Hair color on head does not match the color of their eyebrows",
    "Canine teeth are pointy (like a vampire)",
    "Covered in bug bites, they are quite itchy",
    "Walks with a pronounced limp",
    "Slurs speech like they are drunk, but is otherwise quite lucid",
    "Is craving sweets",
    "Is very hairy, almost a little TOO hairy...",
    "Seems to attract nearby spiders",
    "Recently started hearing voices that aren't there",
    "Can't control their right hand, it does mischievous things",
    "Owns a full-grown bear as a pet",
    "Just killed a person and is trying to hide the body",
    "Always thinks that people are watching them",
    "Unreasonably large kneecaps",
    "Their side weapon (maybe sword), talks",
    "Missing their left hand",
    "Has a very pronounced hunched back",
    "Has severe anxiety",
    "Cannot stop itching",
    "Has an unreasonable fear of cows ever since.... the accident",
    "Is done with your bull-crap",
    "Extremely skinny",
    "Quite fat",
    "Has a weirdly fat face and skinny body",
    "Will spill ALL the beans if intimidated",
    "Is wearing a digital wrist-watch",
    "Knows everything about the world outside of the game",
    "Has a large scar on their upper arm",
    "Looks stoned",
    "Face always has some sort of food on it",
]