secret_list = [ "has a weak heart",
                "is haunted by their grandfathers spirit",
                "is up to their eyeballs in gambling debt",
                "has short term memory loss",
                "is illiterate",
                "is terrible at all forms of combat",
                "can't stand the sight of blood",
                "is overwhelmingly lazy",
                "doesn't know how to ask nicely",
                "has a tattoo marking them as a murderer",
                "habitually wets the bed",
                "comes from a disgraced family",
                "has a problem with a giant spider infestation",
                "has uncontrollable flatulence",
                "thinks healers are out to get them",
                "suffers from narcolepsy",
                "who has multiple spirits living in their head",
                "is plagued with extreme social anxiety",
                "is a pacifist",
                "is being hunted by the city guards",
                "sees via echolocation",
                "insists they are a displaced royal",
                "who was dared to start fights with 16 different strangers",
                "who had a dream where they sw the entire party turned to ash",
                "is cursed with creeping barkskin disease",
                "is possessed by the spirit of an ancient ruler",
                "is the victim of a long con",
                "who can still hear the screams of their evaporating companions",
                "refuses aid in all its forms on principle",
                "spends their spare time writing action novels",
                "insists they are reinventing the wheel",
                "needs to make it to the surface pronto",
                "is prone ato fainting at the sight of blood",
                "knows their potion of fly will only last another hour",
                "is a silver dragon in disguise",
                "has never worked a day in their life",
                "is testing a regenerative treatment that has a 50/50 chance of turning users into a bullywug",
                "is being pursued by a jilted lover",
                "is growing concerted their crystal ball isn't predicting the future so much as manifesting it",
                "has the self-confidence of a soggy biscuit",
                "is terrified they'll be forced to kill again",
                "is slowly losing their ability to speak",
                "is trying to find a place to bury their vampiric mistress",
                "believes they are a great hero from the past reborn",
                "will do anything to obtain power over their father",
                "who can speak with animals (but finds them pretty boring)",
                "has developed blindsight",
                "knows of a forgotten pirate hoard hidden at the bottom of an undergound lake infested with evil fishfolk",
                "knows the ritual they're planning will require blood of at least 2 adventurers",
                "believes they will shortly turn into a troglodyte",
                "has heard there might be an opening for royal advisor",
                "has discovered the mummified corpse of a long-dead necromancer",
                "wants to gain access to other dimensions",
                "has yet to exhibit any evidence that they are anything other than an absolute loony",
                "is on the run from hired killers out for their blood",
                "can literally smell fear",
                "must steal a rare flower that can provide and antidote to their beloved's sickness",
                "thinks they are the smartest person in the room",
                "has been inadvertently luring a grell their way",
                "hasn't yet managed to catch it", #This is the end of the NPC encounters book
                "has sticky fingers",           #This is the begining of the random encounters book
                "is an utter coward",
                "doesn't speak common",
                "is tracking the party's movements for the spy's guild",
                "cannot walk on their own",
                "is plagued by a Curse (see Encounters pg 248)",
                "has lost the will to live",
                "can't control the volume of their voice",
                "is in deep with a local crime boss",
                "is never wrong. Just ask them",
                "is always in a hurry",
                "gets distracted easily",
                "is addicted to a local drug",
                "doesn't believe in violence",
                "distrusts at least one party member",
                "is also a lycanthrope",
                "is allergic to something nearby",
                "is comically hot tempered",
                "is plagued with a small bladder",
                "has terrible judgement",
                "is a satyr in disguise",
                "seeks the perfect whisky recipe",
                "is afraid of the dark",
                "is a stranded planar traveler",
                "is self-obsessed",
                "struggles with their dad's expectations",
                "doesn't have teeth",
                "insults those in charge",
                "a mind that is beginning to unravel",
                "is hopeless at negotiation",
                "is afraid of bats",
                "is part time cult leader",
                "gets nervous near new people",
                "needs locks of hair from everyone",
                "despises being touched",
                "runs a multi-level-marketing scam",
                "is definitely a fiend, but is making it work",
                "can't read",
                "is bad luck to everyone within 30 ft",
                "is possessed by a low level devil",
                "has a gambling problem",
                "has a problem with somnambulism",
                "can't remember their name",
                "is a goose that was polymorphed",
                "lies for fun",
                "is a member of the Assassins' Guild",
                "hasn't paid their tab in 6 months",
                "has never made a true friend",
                "is on the run for tax evasion",
                "is a long lost member of the royal family",
                "is struggling to get over the flu",
                "is a runaway zombie",
                "owns a treasure map to a secret island",
                "hates children",
                "is the very definition of chaotic evil",
                "is afraid of spellcasters",
                "is working against the part's interests",
                "lacks common sense",
                "is being blackmailed",
                "feels like an extra in someone else's story",
                "is wearing a hag's eye from a nearby coven",
                "is five months behind on all their bills",
                "can only tell the truth",
                "is immortal",
                "won't take no for an answer",
                "uses a puppet to talk",
                "has a habit of losing their false teeth",
                "can read minds via touch",
                "may have made a pact with a demon",
                "is way more apathetic than you",
                "fears commitment",
                "assumes everyone they meet is a shifter",
                "is devoid of confidence",
                "is a compulsive liar",
                "is never on time",
                "is particularly awkward",
                "is afraid of heights. And depths",
                "speaks with wild gestures",
                "once rules this land",
                "is a newly made vampire",
                "has crippling arthritis",
                "now has cold feet",
                "won't listen to human opinions",
                "is absolutely from the future",
                "serves a talking cow",
                "was, until today, a shut in",
                "thinks humans are useless",
                "is also a deva",
                "is a magic school dropout",
                "is a warlock of the Great Old One (can speak telepathically)",
                "is a total yes-man",
                "is a happy-go-lucky necromancer",
                "is a budding songwriter",
                "was an escaped convict in their youth",
                "is possessed by the spirit of a god",
                "owns a dog that can speak Common",
                "runs an illegal fighting ring nearby",
                "is an absolute killjoy",
                "once looked completely different" #this is the end of the random encounters book
]