underdark_secret_list = [
    "secret underdark",
    "has a weak heart",
    "is haunted by their grandfathers spirit",
    "is up to their eyeballs in gambling debt",
    "has short term memory loss",
    "is illiterate",
    "is terrible at all forms of combat",
    "can't stand the sight of blood",
    "is overwhelmingly lazy",
    "doesn't know how to ask nicely",
    "has a tattoo marking them as a murderer",
    "habitually wets the bed",
    "comes from a disgraced family",
    "has a problem with a giant spider infestation",
    "has uncontrollable flatulence",
    "thinks healers are out to get them",
    "suffers from narcolepsy",
    "who has multiple spirits living in their head",
    "is plagued with extreme social anxiety",
    "is a pacifist",
    "is being hunted by the city guards",
    "sees via echolocation",
    "insists they are a displaced royal",
    "who was dared to start fights with 16 different strangers",
    "who had a dream where they sw the entire party turned to ash",
    "is cursed with creeping barkskin disease",
    "is possessed by the spirit of an ancient ruler",
    "is the victim of a long con",
    "who can still hear the screams of their evaporating companions",
    "refuses aid in all its forms on principle",
    "spends their spare time writing action novels",
    "insists they are reinventing the wheel",
    "needs to make it to the surface pronto",
    "is prone ato fainting at the sight of blood",
    "knows their potion of fly will only last another hour",
    "is a silver dragon in disguise",
    "has never worked a day in their life",
    "is testing a regenerative treatment that has a 50/50 chance of turning users into a bullywug",
    "is being pursued by a jilted lover",
    "is growing concerted their crystal ball isn't predicting the future so much as manifesting it",
    "has the self-confidence of a soggy biscuit",
    "is terrified they'll be forced to kill again",
    "is slowly losing their ability to speak",
    "is trying to find a place to bury their vampiric mistress",
    "believes they are a great hero from the past reborn",
    "will do anything to obtain power over their father",
    "who can speak with animals (but finds them pretty boring)",
    "has developed blindsight",
    "knows of a forgotten pirate hoard hidden at the bottom of an undergound lake infested with evil fishfolk",
    "knows the ritual they're planning will require blood of at least 2 adventurers",
    "believes they will shortly turn into a troglodyte",
    "has heard there might be an opening for royal advisor",
    "has discovered the mummified corpse of a long-dead necromancer",
    "wants to gain access to other dimensions",
    "has yet to exhibit any evidence that they are anything other than an absolute loony",
    "is on the run from hired killers out for their blood",
    "can literally smell fear",
    "must steal a rare flower that can provide and antidote to their beloved's sickness",
    "thinks they are the smartest person in the room",
    "has been inadvertently luring a grell their way",
    "hasn't yet managed to catch it" #This is the end of the NPC encounters book
]

general_secret_list = [
    "secret general",
    "has sticky fingers",           #This is the begining of the random encounters book
    "is an utter coward",
    "doesn't speak common",
    "is tracking the party's movements for the spy's guild",
    "cannot walk on their own",
    "is plagued by a Curse (see Encounters pg 248)",
    "has lost the will to live",
    "can't control the volume of their voice",
    "is in deep with a local crime boss",
    "is never wrong. Just ask them",
    "is always in a hurry",
    "gets distracted easily",
    "is addicted to a local drug",
    "doesn't believe in violence",
    "distrusts at least one party member",
    "is also a lycanthrope",
    "is allergic to something nearby",
    "is comically hot tempered",
    "is plagued with a small bladder",
    "has terrible judgement",
    "is a satyr in disguise",
    "seeks the perfect whisky recipe",
    "is afraid of the dark",
    "is a stranded planar traveler",
    "is self-obsessed",
    "struggles with their dad's expectations",
    "doesn't have teeth",
    "insults those in charge",
    "a mind that is beginning to unravel",
    "is hopeless at negotiation",
    "is afraid of bats",
    "is part time cult leader",
    "gets nervous near new people",
    "needs locks of hair from everyone",
    "despises being touched",
    "runs a multi-level-marketing scam",
    "is definitely a fiend, but is making it work",
    "can't read",
    "is bad luck to everyone within 30 ft",
    "is possessed by a low level devil",
    "has a gambling problem",
    "has a problem with somnambulism",
    "can't remember their name",
    "is a goose that was polymorphed",
    "lies for fun",
    "is a member of the Assassins' Guild",
    "hasn't paid their tab in 6 months",
    "has never made a true friend",
    "is on the run for tax evasion",
    "is a long lost member of the royal family",
    "is struggling to get over the flu",
    "is a runaway zombie",
    "owns a treasure map to a secret island",
    "hates children",
    "is the very definition of chaotic evil",
    "is afraid of spellcasters",
    "is working against the part's interests",
    "lacks common sense",
    "is being blackmailed",
    "feels like an extra in someone else's story",
    "is wearing a hag's eye from a nearby coven",
    "is five months behind on all their bills",
    "can only tell the truth",
    "is immortal",
    "won't take no for an answer",
    "uses a puppet to talk",
    "has a habit of losing their false teeth",
    "can read minds via touch",
    "may have made a pact with a demon",
    "is way more apathetic than you",
    "is missing their tongue",
    "fears commitment",
    "assumes everyone they meet is a shifter",
    "is devoid of confidence",
    "is a compulsive liar",
    "is never on time",
    "is particularly awkward",
    "is afraid of heights. And depths",
    "speaks with wild gestures",
    "once rules this land",
    "is a newly made vampire",
    "has crippling arthritis",
    "now has cold feet",
    "won't listen to human opinions",
    "is absolutely from the future",
    "serves a talking cow",
    "was, until today, a shut in",
    "thinks humans are useless",
    "is also a deva",
    "is a magic school dropout",
    "is a warlock of the Great Old One (can speak telepathically)",
    "is a total yes-man",
    "is a happy-go-lucky necromancer",
    "is a budding songwriter",
    "was an escaped convict in their youth",
    "is possessed by the spirit of a god",
    "owns a dog that can speak Common",
    "runs an illegal fighting ring nearby",
    "is an absolute killjoy",
    "once looked completely different" #this is the end of the random encounters book
]

outskirts_secret_list = [
    "secret outskirt",
    "emits a screeching noise every time they move", #this starts NPC Outskirts
    "is charming but in an off-putting way",
    "will tell gruesome and violent horror stories any chance they get",
    "ran away from home after a disagreement with their parents",
    "never refuses a date",
    "is a serial arsonist on the run from authorities",
    "must sew someone's mouth shut as repareation to their god",
    "is an undead ghost king in disguise",
    "knows the location of a secret gold panning spot",
    "gets incredibly excited about their research",
    "cant speak common",
    "has 24 hours to deliver or else their reputaion will be ruined",
    "is a skeleton lose from its necromancer",
    "will tell you the name of all 44 sheep under their care",
    "is a master wizard",
    "will eat any kind of meat. ANY kind",
    "is the heir to a multi-realm fur coat corparation",
    "is cursed to play the panpipes forevermore",
    "who can't stop tripping over their footwear",
    "is an elite salesperson who has marked up their goods to ridiculous prices",
    "is considered untouchable by the criminal element",
    "left their coin purse in a town that's nearly a week's ride from here",
    "is leaking",
    "and find their hidden candle of invocation",
    "whose pet is actually a familiar",
    "plans to murder their spouse",
    "can lead you to a wizard's tomb",
    "is desirous of a way to retur others from the dead",
    "will turn into a were-tiger at night",
    "is possessed by a ghost",
    "will sacrifice and innocent to attain their goals",
    "has contingency plans to fake their own death",
    "has no sense of smell",
    "has a cursed knife that requires the blood of a new victim every 24 hours",
    "has a map with an 'X' on it",
    "has a scroll they can't read",
    "has just ingested a handful of hallucinogens",
    "knows of a sunken temple overflowing with riches",
    "is wanted for murder",
    "knows where to find 1,000 gp",
    "is in danger of being fired from the fish sorting factory",
    "has a tendency to scream and spit while speaking",
    "plans to poison those in their care whom they perceive to be suffering",
    "can't carry a tune to save their life",
    "has just snatched a ransom note",
    "woke up to find their nose was gone",
    "has added a highly addictive ingredient to their supply",
    "has started seeing strange faces in mirrors",
    "doesn't know they died",
    "thinks it may have something to do with a red-eyed boar they killed",
    "is prepared to poison all the freshwater within 100 miles",
    "is trying to scream down the sun",
    "whose father was killed by a vengeful son",
    "needs an extra set of hands",
    "has the key to a forbidden treasure",
    "is particularly fond of anyone willing to kill on their behalf",
    "still has all the keys from their escape from prison",
    "is attempting to attract lost souls to this location",
    "will be killed the moment that they stray from their mission",
    "will transform into a sea hag momentarily"                         #End of NPC outskirts
]

small_town_secret_list = [
    "secret small town",
    "wants vengeance on the child who betrayed them",                    #Start of NPC small town
    "has an evil twin",
    "thinks they might be able to get away with murder one last time",
    "who can't stop asking a member of the party if they have met",
    "can dance better than anyone else in town",
    "who is certain they can cure zombification",
    "has no social skills to speak of",
    "has a map that leads to a long-lost treasure",
    "is obsessed with hunting the shark who killed their father",
    "dosen't seem to understand that life is precious",
    "can't stop shouting expletives",
    "hide the fact that they are incontinent",
    "dosen't realize they're cursed to be alone",
    "whose false teeth were recently animated by a local bard",
    "has a hard time avoiding trouble",
    "has two siblings who wish them dead",
    "wants to get into local politics",
    "can't fight their way out of a paper bag",
    "forgot where they buried a priceless stash of truffles",
    "is showing the first signs of lycanthropy",
    "is being stalked in their dreams",
    "suffers from extreme claustrophobia",
    "and to determine whether or not to kill the king/queen",
    "hasn't got the energy to walk more than 50 yards without a rest",
    "was at one time an exotic dancer",
    "finds danger intoxicating",
    "suffers from a horrible case of fleas",
    "has lost their hearing in one ear",
    "or they wont inherit a vast piece of land",
    "has a secret that could lead to war",
    "doesn'y realize they will be dead in 20 minutes",
    "suffers from terrible allergies",
    "has a dagger instead of a hand",
    "needs a human skull for an idea they have",
    "was paid to distract the gaurds",
    "has several thousand gold peices hidden away",
    "who hears a voice that keeps saying \"Just bloody do it!\"",
    "has a magic wepon they haven't learned how to wield",
    "who angered the wrong farmer's daughter",
    "thinks they might be a deity",
    "who collects body parts for fun...honest",
    "has secured an apprenticeship with the local necromancer",
    "is about ready to skip town",
    "is getting nervous about the coming eclipse",
    "who is a \"strike first, sort it out later\" kind of citizen",
    "knows the perfect loaf is the enemy of the good",
    "who doesn't know the value of anything they possess",
    "insists they will grow up to be a lawyer for dragons who have been robbed",
    "struggles with perfomance anxiety",
    "is half-harpy",
    "but can't get near water without having flashbacks",
    "who is lobbying for a parlay with the local ogres",
    "who has an above average Constitution",
    "is one of the realm's most revered martial artists",
    "is the servant of a local mountain hag",
    "who has had their leg broken by a local gang",
    "has a reputation as a con artist",
    "is planning to start their own adventurer-for-hire business",
    "is here to start a coup",
    "who cannot die"                        #End of NPC small town
]



secret_lists = [general_secret_list, small_town_secret_list, outskirts_secret_list, underdark_secret_list]