underdark_wants_list = [
    "wants underdark",
    "who believes they are due a promotion with the city guard",
    "who has a dream of opening a bakery",
    "who is working on a new theory of economics",
    "who is a big fan of romance novels and wants to collect them all",
    "wo seeks to convert passerby's to their religion",
    "who needs to rescue their kidnapped sister",
    "who wants ot become a champion fistfighter",
    "who is seeking to gain their father's respect as a successful miner",
    "who is trying to find someone to escort them to the top of an undermountain",
    "who needs to beg everyday to make ends meet",
    "who is eager to get married",
    "who wants to get their painting featured in a museum",
    "who just wants to keep his mine running",
    "who is looking to fit into high society",
    "who needs medical attention to cure them of a disease",
    "who desires vengeance on the goblin tribe that killed their family",
    "who wants to own a house in the poshest area of town",
    "who is trying to figure out who burled their home",
    "who wants to be a great warrior",
    "who wants to break into the royal treasury",
    "who is looking for a large conformable cavern",
    "who is searching for the royal family",
    "who is looking for trouble",
    "who is searching for a legendary black tower",
    "who needs to find a cure before it is too late",
    "who heard rumors about a magical deck of cards and has come to investigate",
    "who is following a map with a big X marked in the center",
    "who is on a mission to stamp out evil and rescue their friends from the shadow plane",
    "who got lost on their way to the nearest settlement",
    "who is looking for inspiration and excitement",
    "who is searching for investor in their startup",
    "who has found a new use for bat droppings",
    "wio must defeat Krag the Malevolent in one-on-one combat to claim the throne",
    "who is ready to compete in the Great Cliff Dive",
    "who just wants to tak to anything vaguely humanoid",
    "who wants to open the first subterranean sky port",
    "who is searching for participants for a clinical trial",
    "who is looking for the rare white dragon bush, said to make delectable tea",
    "who needs to follow their crystal ball's will",
    "who dreams of being a model for Cavernguy, the underrealm's top fashion brand",
    "who has a cursed dagger they need to unload",
    "who recently went swimming in a golden pond",
    "dragging a coffin that looks to be full",
    "who seeks vengeance for a brutal attack that left their village decimated",
    "who has tried for years to converse with demons",
    "who has developed a recipe for the world's best cheese and honey pie",
    "who knows the truth about the Heir of Isnholm",
    "who is obsessed with building a vessel that can move underwater",
    "who believes the son they lost to an underground whirlpool years ago is still alive",
    "who needs someone to kill the sorcerer who has cursed them",
    "who is looking for a way to gain the ear of the queen",
    "who seeks a way to speak with the dead",
    "who is trying to make a living off performing quickie weddings",
    "who believes they are the reincarnation of a legendary wizard",
    "who would like to regain their memory of the past 10 years",
    "who thirsts for combat because intellectual pursuits are for fools and cowards",
    "who needs to infiltrate a fortress-like dark elvin city",
    "who has a money making scheme involving a small sedated red dragon and a pipe organ",
    "who is certain they are headed down the right tunnel",
    "who thinks they have discovered a new bat species"   #this is the end of the NPC book
]

general_wants_list = [
    "wants general",
    "who could really use a hug",                           #this is the begining of the random encounters book
    "who could use a bath",
    "who literally and figuratively has no sense of direction",
    "who is begging for help to find their gnoll-nabbed dad",
    "who is compelled to smell everyone they meet",
    "who just needs a ride into/out of town",
    "who thinks they're possessed by a vengeful warrior",
    "who needs a cure for their incessant hiccups",
    "who has developed a taste for human flesh",
    "who is just trying to get through the day, man",
    "who knows of a nearby cave filled with treasure",
    "who hasn't slept in eight days",
    "who hasn't been sober in two weeks",
    "who will do pretty much anything for a silver piece",
    "who repeats the full names of everyone they meet",
    "who cant stop talking about the end of the world",
    "who is constantly on the lookout for grooming tips",
    "who compulsively says what they are thinking",
    "who wants to do right by their god, no matter the cost",
    "who is attracted to a member of the party",
    "whose brother was wrongfully accused",
    "who thinks they have a rat infestation",
    "who keeps hearing voices in their head",
    "who can't find their horse",
    "who needs a set of blacksmith's tools",
    "who lost their mother's wedding band ",
    "who needs to be the center of attention",
    "who needs help with a dance off",
    "who had a dream where they saw the party die",
    "who needs a rare coin to complete their collection",
    "who loves to talk about food",
    "who owns the town paper",
    "who wants to be left alone",
    "who is worried they might have unleashed a curse",
    "who needs human contact",
    "who says their family has been possessed",
    "who just wants to own their own pastry shop",
    "who needs a place to hide",
    "who is looking for the witch of the woods",
    "who is trapped in the friend zone",
    "who is saving to start a restaurant",
    "who wants this uptight town to legalize dancing",
    "who suspects their house is haunted",
    "who wants to clean up a pond",
    "who says their sister has been turned into a dog",
    "who wants to know if you have seen a man named Reb",
    "who has a standup performance tonight",
    "who needs some help dealing with local bullies",
    "who wants the party to protect them",
    "who needs an invitation to tonight's ball",
    "who is looking to cure a contagious disease",
    "who is searching for the power of a wish spell",
    "who has been challenged to a rap battle",
    "who just inherited an orphanage",
    "who is raising money for wizard school",
    "who can't find their glasses",
    "who is on the hunt for a red dragon egg in the area",
    "needs to catch six fish",
    "who needs everyone to wise up",
    "who needs to acquire a rare ochre jelly",
    "who believes their friend might be a hag",
    "who is looking for models for a fashion show",
    "who wants to join the circus",
    "who needs enough incense to bring back their familiar",
    "who is looking for some drinking buddies",
    "who can't unlock their basement",
    "who refuses to bathe and talks to any stray dogs",
    "looking for the Dream Archive (Encounters book pg 118)",
    "who seeks to kill the town guard who killed their dad",
    "who would rather be listening to heavy lute tunes",
    "who wants to learn to fight",
    "who enjoys harmless flirting",
    "who spreads propaganda against shapechangers",
    "enroute to the Hall of Many Gods (Encounters book pg 144)",
    "who needs investors for their pyramid scheme",
    "who can't find their watch",
    "who is trying to sell a dragon heart",
    "who wants to spread the word about their god",
    "who is trying to write a love ballad",
    "searching for redemption",
    "who wants to see the next sunrise",
    "who longs to be the strongest person alive",
    "hired to kill a party member",
    "who compulsively judges other's fashion sense",
    "who is trying to build a time machine",
    "who is on a quest to kill monsters",
    "who is trying to do good",
    "who is trying to sell some fruit",
    "who is on the run from prison",
    "who needs to blood of 30 crows",
    "who wants to learn Common",
    "who wants to go on an adventure",
    "who is peddling bags of a medicinal root",
    "who needs to spread their father's ashes",
    "who is hoping to run for public office",
    "who seeks a new owner for their pet owl",
    "who is looking for their dog. Have you seen their dog?",
    "who doesn't let anyone get in their way",
    "who is hunting for ancient relics in old forgotten tombs",
    "who is looking for inspiration for their new novel" #this is the end of the random encounters book
]

outskirts_wants_list = [
    "wants outskirts",
    "who is seeking oil or some other form of lubrication", #This is the start of NPC outskirts
    "is searching for deserters of the royal army",
    "is a ghosthunter hunting ghosts",
    "is looking for a place to stay for the night",
    "wants to ride a dragon",
    "wants to burn everything",
    "who is wandering the wilderness as a simple hermit",
    "who is searching for their beloved",
    "who is a gold panner looking for the next big win",
    "who is a researcher of monster poisons and venoms",
    "who is tracking down an insane werewolf",
    "who wants to know if you have seen the yeti",
    "who is searching for a nice patch of dirt to lay down in",
    "who is looking for better pastures",
    "who is searching for a tower to spend their retirement",
    "who needs meat to keep them going",
    "who is looking for bears to make coats",
    "who wants to solve your rat problem",
    "who is just seeing where the path takes them, man...",
    "who wants to sell you a second-hand cart",
    "who gets sick pleasure out of kicking others' shins",
    "who needs a new horse",
    "who is trying to raise interest in giant jousting",
    "who needs to break into a remote prison",
    "who is looking for a lost cat",
    "who can't wait for their wedding day",
    "who must remember something that's been forgotten",
    "who seeks arcane knowledge related to their birthmark",
    "who needs their magic serum",
    "who dreams of being a knight",
    "who needs to appease their god or goddess",
    "who needs to pay off a masive debt",
    "who needs a bath",
    "who seeks an artifact that can alter reality",
    "who has a great story to tell",
    "who wants nothing more than to be a vampire",
    "who needs a safe place to hide",
    "who is looking for a ship and a start to sail her by",
    "who's looking for safe passage out of the area",
    "who wants their freedom from an arranged marriage",
    "who is searching for a spell that allows subjects to grow extra limbs",
    "who is searching for a lost or stolen pet capybara",
    "who wants to bring peace to all",
    "who want to become a bard",
    "who enjoys pickpocketing strangers",
    "who wants to win a beauty pageant",
    "who wants to boost their cheese sales",
    "who enjoys stealing from the dead",
    "who is destined to save their village",
    "who needs to get rid of the two painful welts on either side of their head",
    "who brings tidings from the sea serpent Dakkfoarian",
    "who can't stop staring at the sky",
    "who is here to kill the man who killed their father",
    "who is dealing with a serious crab infestation",
    "who is on the run from another realm",
    "who is ready to meet a worthy suitor",
    "who desires revenge on their lab dwelling creator",
    "who claims to serve as a human lighthouse",
    "who knows the truth about what the party seeks",
    "who is here to repay a debt"                       #The end of NPC outskirts
]

small_town_wants_list = [
    "wamts small town",
    "who desires a warrior to help reclaim their world",
    "who is the only representative of their race in the region",
    "who wants an apprentice",
    "who desperately wants to remember who they are",
    "who never met a pie they didnt like (or want to steal a peice of)",
    "who needs to find a magic potion that they lost",
    "who wants to unite the area's clans",
    "who wants to learn how to read a map",
    "who wants a ship and a star to sail her by",
    "who wants a sign that their god really exists",
    "who is in search of their missing family",
    "who needs to exert their dominance over everyone they meet",
    "who just wants the love of a good woman",
    "who is training to become a priest",
    "who seeks high adventure and bold companions",
    "who wants to steal something really valuable",
    "who needs a rare frog's blood to concoct a poison",
    "who wants the townspeople to fear them",
    "who would like a canine companion",
    "who wants a cure for the hair on their back",
    "who just wants a good nights sleep",
    "who dreams of becoming a giant slayer",
    "who just needs a day off",
    "who seeks retribution for a move against them",
    "who thinks they should be running the show",
    "who desires forgiveness for the fire they started",
    "who wants to keep humans from encroaching further on the wild",
    "who needs a special cheese for a fondue they're making",
    "who needs to get married within the next three days",
    "who isn't happy with their current station in life",
    "who needs to get a bad wound attended to",
    "who needs the purse on that man's belt",
    "who desires their neighbor's spouce",
    "who believes they are the reincarnation of a great mage",
    "who loves the chase",
    "who is trying to lay low and avoid the tax collector",
    "who just wants to be left alone",
    "who is a powerful bard in disguise",
    "who needs a bath more than anything",
    "who's searching for a holy tree guarded by a magical snake",
    "who is searching for some \"fine specimens\"",
    "who would do anything to escape this backwater",
    "who can't find their house keys",
    "who is workshopping their new life philosophy called \"Roll with it\"",
    "who vehemently protests against vegetarianism and chance they get",
    "who needs to bake another 568 loves before the weeks end",
    "who is wondering if you'd like to buy some junk",
    "who is studying via carrier pigeon to become a barrister",
    "who is looking for their next gig",
    "who just wants to chat about birds",
    "who only wants to go fishing",
    "who is definitely not an orgre in disguise",
    "who is offering free samples",
    "who is looking for any kind of work",
    "who will offer payment for information",
    "who is a master acrobat street performer",
    "who has a line on a fortune and knows you won't believe them",
    "who won't shup up about the debt",
    "who wants directions to the local noble's estate",
    "who recently crawlded out of the pond they'd been dumped in"       #End of NPC Small town
]


wants_lists = [general_wants_list, small_town_wants_list, outskirts_wants_list, underdark_wants_list]