color_list = [
    "blood red",
    "royal purple",
    "japanease cherry blosum",
    "construction cone orange",
    "olive tree green",
    "mac and cheese yellow",
    "poop brown",
    "snot green",
    "charcol black",
    "off white (almost bony)",
    "Dead leaf brown",
    "cyan",
    "pitch black",
    "glittering gold",
    "sparkling silver",
    "sparkling star blue",
    "jaunadice yellow",
    "fire truck red",
    "bright blue",
    "rusted rose red",
    "deep green",
    "tye dye",
    "crossing guard orange",
    "granular grey",
    "flamingo pink",
    "royal blue",
    "Moldy Green",
    "Sterling Silver",
]