smells_list = [
    "poop",
    "normal",
    "freshly cut flowers",
    "worked leather",
    "nickles",
    "fresh bread",
    "something suspicious",
    "victory",
    "defeat",
    "warm cheese",
    "old milk",
    "dead mouse",
    "dead fish",
    "Vegitation",
    "spicy",
    "Throw up",
    "old eggs",
    "raw chicken",
    "lavender",
    "fresh rain",
    "Honeysuckle",
    "Expensive Perfume",
    "Freshly laundered clothes",
    "chlorine",
    "Campfire",
    "Smoke",
    "Bacon",
    "Chocolate",
    "Dry airy smell of desert",
    "Cactice Juice",
    "Coconuts",
    "Oranges",
    "Alcohol",
]