carrying_list = [ "15cp, 2sp; a shirt of chainmail",
                  "40cp, 10gp; a lockpicking kit",
                  "50cp, 5sp; a luxurious cloak",
                  "5sp, 2gp; an emerald ring",
                    "34cp; a bottle of liquor",
                    "10cp, 4sp; a healing potion",
                    "20cp; a pair of brass knuckles",
                    "15cp, 3sp; a ball of string",
                    "4cp; a bundle of bread and cheese; a dagger",
                    "Soiled rags; an old war medal",
                    "2sp, 5gp; a swordfish",
                    "20cp, 1pp; a book of sketches",
                    "1cp, 10sp; an empty knapsack",
                    "5gp, 2pp; a book on dwarven etiquette",
                    "30cp; a pair of boots; a map of secret tunnels",
                    "20cp, 5sp; a love letter from their sister-in-law",
                    "30cp, 2sp, 3gp; a prayer idol",
                    "17cp, 10sp; acceptance letter from the Academy of Scholars",
                    "20cp; a whetstone",
                    "5gp; two disguise kits",
                    "10cp, 6sp; and assortment of cave fruit",
                    "3cp; expensive and muddy purple robes",
                    "12cp; 4sp; chewing tobacco; +1 hand wraps",
                    "23sp, 58gp; potion of heroism",
                    "3cp; 7gp; flaking bark bits; a potion of healing",
                    "2cp, 42sp, 98gp; a solid gold puzzle box in the shape of a pyramid; a deck of rare playing cards",
                    "9cp, 2sp; a pseudodragon; a (potentially) real treasure map",
                    "5cp, 8sp; 8 throwing knives; a jade carving of a toad",
                    "43cp, 64sp; an ox cart; 100gp worth of organic vegetables",
                    "3cp, 5sp; a royalty statement for 34gp; 3 manuscripts",
                    "4cp, 78gp; a pitch for square wheels; a 5 year plan",
                    "1cp; a massive jug of guano",
                    "18cp, 9sp, 2gp; a romance novel titled In the Enemy's Embrace",
                    "34cp, 7gp; 3 vials of alchemist's fire; a token of feather fall",
                    "469gp, 86pp; a diary written in stream of consciousness and spanning 430 years",
                    "23cp, 5sp, 290gp a drafted business application; a bottle of gin",
                    "59sp, 81gp; several vials of viscous liquids; a large needle",
                    "3cp, 7sp; a large collection of rare tea leaves, a cast iron tea pot",
                    "5cp, 8gp; a book titled Crystal Reading for Dummies; a large crystal ball worth 990gp",
                    "2sp, 6gp; the spring fashion catalogue for 'Cavernguy'",
                    "12sp, 14gp; a +1 dagger; bag of live insects for snacking",
                    "8cp, 11sp; a dream journal filed with wild visions",
                    "12sp, 13gp; a blank piece of parchment that when heated reveals a curious map of the underworld with an 'X' on it",
                    "2gp, 4pp; a short sword; silver dragon head pendant on a short chain worth 120gp",
                    "32gp; 6 tattoo needles; 4 bottles of ink; curved dagger",
                    "14sp, 16gp; mushroom-based incense that stops pain when inhaled (6 uses good for 8 hours each)",
                    "32cp, 6sp; steel waking stick/spear (1d8 piercing)",
                    "16gp; mechanical drawings; a map of an underground lake; and underwater breathing apparatus",
                    "14sp, 18gp; a ritual dagger; two empty vials",
                    "2sp, 4gp; full wineskin; a charcoal sketch of their former self",
                    "12sp, 22gp; 2 rings worth 50gp each; several fine silk handkerchiefs",
                    "10sp, 11gp; a jar of wax, flint and steel",
                    "22sp, 10gp; a box of two dozen matching rings worth 18gp; a tie-dyed stole",
                    "10sp; necklace with cheap bronze medallion; dagger hilt with no blade",
                    "21sp, 12gp; dagger hidden in boot (1d4 slashing damage)",
                    "17sp, 4gp; brass knuckles; small pencil; journal inscribed with poems",
                    "5sp, 8gp; bag stuffed with a cloak of invisibility",
                    "12sp, 38gp; salve that conveys fire resistance (2 uses)",
                    "38sp, 40gp; large pouch; small dagger",
                    "35cp, 20sp; a tattered book titled Rare Bats of the World; a broken holy symbol", #this is the end of the NPC book
                    "14cp,5sp,2gp; Belt-knife; scythe; bundle of wheat",                 #This is the beginning of the random encounters book
                    "Empty Money pouch; a silver broach in the shape of a rabbit",
                    "8cp, 1sp; Small bag of butterfly wings; pouch of herbs and a pipe",
                    "15cp, 1gp;a novel titled Through the Weave; One packet of beans",
                    "Nothing and proud of it",
                    "17cp, 2sp; A wooden cup they carved themselves",
                    "73cp painted to look like 73pp; a small jar of platinum paint",
                    "32cp, 13sp; a hoop and a stick",
                    "15sp; a necklace that contains a ball of yak hair",
                    "21cp, 2sp, 3gp; an incredibly smooth rock they enjoy tumbling",
                    "3sp, 8gp; a jar full of beef tallow; a crude map of the region",
                    "5cp, 9sp, 1gp' a vial of wyvern poison",
                    "4cp, 16sp; an oversized lollipop; a deck of cards",
                    "6cp, 8sp, 12gp; Loaded dice; a directory of local gambling halls",
                    "9cp, 2sp; knitting needles and a half finished scarf",
                    "7cp; a large leather hat; a set of thieves' tools",
                    "6sp, 1gp; a cup and ball game; trout in butcher paper",
                    "4cp, 3sp, 1gp; a book about blacksmithing",
                    "85cp; a note that says, \"Be careful, I love you. -Mum\"",
                    "64sp; 12gp in loose gems; a rock-hammer",
                    "14cp, 17cp, 4gp; a magnifying glass",
                    "10sp,; brewer's kit and waterskin of whiskey",
                    "32cp; a collection of dolls that look like the party",
                    "A whistle only a badger named Jenny can hear",
                    "5cp, 30sp, 9gp; a very small hat",
                    "19cp, 2sp; a spyglass that can suck out an eyeball on command",
                    "14cp, 92sp; and error filled map of the realm",
                    "A cursed pen knife (Look at curse table encounters book page 248)",
                    "32cp, 7sp, 3gp; A pair of shoes in need of resoling",
                    "8cp; and IOU that reads \"Owe you three sacks of wool. Hamm\"",
                    "94cp, 1gp; A mask that hides their face and a hit list of local thugs",
                    "7cp, 8sp, 2gp; A dark artifact (could be a corrupted artifact)",
                    "34cp, 10sp; a broken lute; a crumpled love letter",
                    "3cp, 5sp, 7gp; a sack of dates; a pound of dried apricots; a fishing pole",
                    "4cp, 6sp; a set of wooden teeth",
                    "7cp, 92sp; a bottle of baby tears they want to sell",
                    "9cp, 53sp, 900gp; A dark leather tome titled How to Act Human",
                    "5cp, 5sp, 5gp; five rings worth 55gp",
                    "3cp, 81sp; Joiner's tools; a blood-soaked rag",
                    "32cp, 5sp, 1pp; a crust of moldy bread; some salted pork",
                    "45cp, 2sp; and undead hand that is very important to them",
                    "61cp, 3sp; a forgers kit; a lost of nobles names",
                    "92cp, 3gp; cufflinks that conceal to doses of Drow poison",
                    "52cp; a sack of fingernails (each more precious than the last)",
                    "89cp, 3sp; a belt buckle with a hidden lock-pick",
                    "62cp, 32sp; a diamond that appears to be worth 500gp (its not)",
                    "25cp, 6sp, 24gp; a sport, the first of its kind",
                    "6cp, 2gp; A sandwich made of nut butter and smashed jam",
                    "21cp, 5sp; an exquisite dagger carved from the bones of a dragon born",
                    "4cp, 74sp; a wineskin willed with a potion of haste",
                    "8cp,53sp; a fake beard; a tome filled with gift ideas for hundreds of children",
                    "91sp; A recipe for pot pie; a small sack of peas; spices;",
                    "3cp 14sp; A jar of honey; A box containing a large queen bee",
                    "7cp, 13sp; a gate spell scroll",
                    "A pocket sized copy of the realm's founding documents",
                    "A frog (roll a d6, on a 1, it was once a prince)",
                    "31cp; a rudimentary coloring book; some colored wax pieces",
                    "4cp, 3sp, 2gp; A set of woodworker's tools",
                    "8sp, A minor gem worth 1gp",
                    "5gp; a +1 scimitar engraved with the name \"Trevor\"",
                    "42sp; A tub of grease; a wand of webs",
                    "55gp; a vial of de-aging serum that takes 20 years of a creatures life",
                    "8sp, 4gp; a tophat concealing a dozen squirrels",
                    "3sp; a bottle of milk; an ornate quarterstaff",
                    "And unopened letter challenging them to a duel with a merchant",
                    "15cp; a jar capable of storing memories",
                    "8cp; a vial labelled \"DO NOT OPEN\" that contians the expelled gas of a king",
                    "90sp; a liniment that helps with insomnia",
                    "13cp; directions to a guard's house; a box of juice",
                    "Sheet music from a bard you've never heard of; a -1 charisma pinky ring",
                    "13pp; a jar of beard oil that is also flammable",
                    "29sp; a small painting of an elven girl",
                    "35cp; a colorful piece of chewing taffy that never loses its flavor",
                    "A list of several gods with at least nine crossed out",
                    "14 vials of a potion that smells great, but does nothing",
                    "a watch chain; a pair of fancy hair combs",
                    "a note with the location of a dragon's lair",
                    "30sp; A pair of bi-leansed readers; a sack of candies",
                    "a mourning ring featuring the eye of their mother",
                    "1cp, 1sp, 1gp, 1pp; a deck of many things",
                    "390gp; a sack of grave dirt; a spade; a beret",
                    "42cp, 71sp,; 3 vials of a tonic that adds +2 to strength for an hour",
                    "62cp, 21sp, 92gp; a gag and hood; 2 vials of purple worm poison",
                    "3cp, 9sp, 21gp; and opal carved in the shape of a jawbone",
                    "5cp; a sport's almanac",
                    "92sp; Manticore bait; a griffon call; sacks of meat",
                    "a 20% coupon for mage you look (Random encounters book pg 128)",
                    "18cp, 4sp; a stuffed tiger; a tuna sandwich",
                    "3cp; a speckled egg; a broken music box;",
                    "92gp; a small heart in a smaller cage;",
                    "3gp; a bag of salt; a bag of pepper; a bag of octopus tentacles",
                    "a lyre that's missing all but one string",
                    "a glass orb; a raven's beak; a vial of tiger blood",
                    "5cp; a lump of coal; a small box filled with ashes",
                    "52sp; an herbalist's kit; a neatly folded poster with their face on it",
                    "5,256gp; a notebook listing all the things they've done this year",
                    "13sp, 2gp; a few gnarled balls of thick cord and cloth",
                    "81cp, 3sp; a list of rules for something called \"Brawl Joint\"",
                    "Ink that disappears but can be revealed with a little heat",
                    "a 32-page booklet of so-called \"haters\" with a few names crossed off" #This is the end of the random encounters book
]