tavern_look_list= ["sawdust on the floor and dust in the rafters",
                   "there is a wait time of 20 mins per drink given their complexity",
                   "and hosting a sing-a-long night with one of the region's least popular bards",
                   "featuring a brand ambassador for an experimental mead",
                   "hiding an illegal gambling hall under the floorboards",
                   "with velvet-lined walls, a dress code and an undeserved air of importance",
                   "with ornamental trophies from beasts and monster hanging on the walls",
                   "and devoid of tables and chairs, its floor stocked with dozens of pillows",
                   "and is less of a bar and more of a dance hall, with music so loud it is hard to hear anything else",
                   "with a black patio that is never open",
                   "with an epic collection of classic board games from the party's childhood, though most sets are missing a peice or two",
                   "with a large, crater-like hole in the center of the floor that has gone unremarked upon for months",
                   "is utterly pleasing to the eye, but ot those trainied in the arcane, is clearly dripping with illusionary magic",
                   "to those familiar with this sort of thing, clearly has an arrangement with a nearby brothel",
                   "with a tropical theme, with drinks and uniforms to match, and feels like walking through a humid rainforest",
                   "with walls lined with sketches depicting famed adventurers and leaders from across the realm enjoying a pint here",
                   "featuring servers who are enthusiastically invested in their job, wearing several kitchy buttons and pushily advertising the bars other locations throughout the realm",
                   "only serves pitchers",
                   "has been named best pub in town several times in a row by nobles in the region, a fact its proprietor is quick to remind anyone who enters at least twice",
                   "features great food at incredible prices, but discriminates against a specific type of customer at GM discression",
                   "with plain walls and smells like new wood. It looks like this place was just built",
                   "with colored lights flying around the tavern to try to make it look like the fey wilds",
                   "the bartender will emphisize that they only sell food, and not drinks, but when pressed will serve drinks"
]