wants_list = ["who believes they are due a promotion with the city guard",
              "who has a dream of opening a bakery",
              "who is working on a new theory of economics",
              "who is a big fan of romance novels and wants to collect them all",
              "wo seeks to convert passerby's to their religion",
              "who needs to rescue their kidnapped sister",
              "who wants ot become a champion fistfighter",
              "who is seeking to gain their father's respect as a successful miner",
              "who is trying to find someone to escort them to the top of an undermountain",
              "who needs to beg everyday to make ends meet",
              "who is eager to get married",
              "who wants to get their painting featured in a museum",
              "who just wants to keep his mine running",
              "who is looking to fit into high society",
              "who needs medical attention to cure them of a disease",
              "who desires vengeance on the goblin tribe that killed their family",
              "who wants to own a house in the poshest area of town",
              "who is trying to figure out who burled their home",
              "who wants to be a great warrior",
              "who wants to break into the royal treasury",
              "who is looking for a large conformable cavern",
              "who is searching for the royal family",
              "who is looking for trouble",
              "who is searching for a legendary black tower",
              "who needs to find a cure before it is too late",
              "who heard rumors about a magical deck of cards and has come to investigate",
              "who is following a map with a big X marked in the center",
              "who is on a mission to stamp out evil and rescue their friends from the shadow plane",
              "who got lost on their way to the nearest settlement",
              "who is looking for inspiration and excitement",
              "who is searching for investor in their startup",
              "who has found a new use for bat droppings",
              "wio must defeat Krag the Malevolent in one-on-one combat to claim the throne",
              "who is ready to compete in the Great Cliff Dive",
              "who just wants to tak to anything vaguely humanoid",
              "who wants to open the first subterranean sky port",
              "who is searching for participants for a clinical trial",
              "who is looking for the rare white dragon bush, said to make delectable tea",
              "who needs to follow their crystal ball's will",
              "who dreams of being a model for Cavernguy, the underrealm's top fashion brand",
              "who has a cursed dagger they need to unload",
              "who recently went swimming in a golden pond",
              "dragging a coffin that looks to be full",
              "who seeks vengeance for a brutal attack that left their village decimated",
              "who has tried for years to converse with demons",
              "who has developed a recipe for the world's best cheese and honey pie",
              "who knows the truth about the Heir of Isnholm",
              "who is obsessed with building a vessel that can move underwater",
              "who believes the son they lost to an underground whirlpool years ago is still alive",
              "who needs someone to kill the sorcerer who has cursed them",
              "who is looking for a way to gain the ear of the queen",
              "who seeks a way to speak with the dead",
              "who is trying to make a living off performing quickie weddings",
              "who believes they are the reincarnation of a legendary wizard",
              "who would like to regain their memory of the past 10 years",
              "who thirsts for combat because intellectual pursuits are for fools and cowards",
              "who needs to infiltrate a fortress-like dark elvin city",
              "who has a money making scheme involving a small sedated red dragon and a pipe organ",
              "who is certain they are headed down the right tunnel",
              "who thinks they have discovered a new bat species",   #this is the end of the NPC book
                "who could really use a hug",                           #this is the begining of the random encounters book
                "who could use a bath",
                "who literally and figuratively has no sense of direction",
                "who is begging for help to find their gnoll-nabbed dad",
                "who is compelled to smell everyone they meet",
                "who just needs a ride into/out of town",
                "who thinks they're possessed by a vengeful warrior",
                "who needs a cure for their incessant hiccups",
                "who has developed a taste for human flesh",
                "who is just trying to get through the day, man",
                "who knows of a nearby cave filled with treasure",
                "who hasn't slept in eight days",
                "who hasn't been sober in two weeks",
                "who will do pretty much anything for a silver piece",
                "who repeats the full names of everyone they meet",
                "who cant stop talking about the end of the world",
                "who is constantly on the lookout for grooming tips",
                "who compulsively says what they are thinking",
                "who wants to do right by their god, no matter the cost",
                "who is attracted to a member of the party",
                "whose brother was wrongfully accused",
                "who thinks they have a rat infestation",
                "who keeps hearing voices in their head",
                "who can't find their horse",
                "who needs a set of blacksmith's tools",
                "who lost their mother's wedding band ",
                "who needs to be the center of attention",
                "who needs help with a dance off",
                "who had a dream where they saw the party die",
                "who needs a rare coin to complete their collection",
                "who loves to talk about food",
                "who owns the town paper",
                "who wants to be left alone",
                "who is worried they might have unleashed a curse",
                "who needs human contact",
                "who says their family has been possessed",
                "who just wants to own their own pastry shop",
                "who needs a place to hide",
                "who is looking for the witch of the woods",
                "who is trapped in the friend zone",
                "who is saving to start a restaurant",
                "who wants this uptight town to legalize dancing",
                "who suspects their house is haunted",
                "who wants to clean up a pond",
                "who says their sister has been turned into a dog",
                "who wants to know if you have seen a man named Reb",
                "who has a standup performance tonight",
                "who needs some help dealing with local bullies",
                "who wants the party to protect them",
                "who needs an invitation to tonight's ball",
                "who is looking to cure a contagious disease",
                "who is searching for the power of a wish spell",
                "who has been challenged to a rap battle",
                "who just inherited an orphanage",
                "who is raising money for wizard school",
                "who can't find their glasses",
                "who is on the hunt for a red dragon egg in the area",
                "needs to catch six fish",
                "who needs everyone to wise up",
                "who needs to acquire a rare ochre jelly",
                "who believes their friend might be a hag",
                "who is looking for models for a fashion show",
                "who wants to join the circus",
                "who needs enough incense to bring back their familiar",
                "who is looking for some drinking buddies",
                "who can't unlock their basement",
                "who refuses to bathe and talks to any stray dogs",
                "looking for the Dream Archive (Encounters book pg 118)",
                "who seeks to kill the town guard who killed their dad",
                "who would rather be listening to heavy lute tunes",
                "who wants to learn to fight",
                "who enjoys harmless flirting",
                "who spreads propaganda against shapechangers",
                "enroute to the Hall of Many Gods (Encounters book pg 144)",
                "who needs investors for their pyramid scheme",
                "who can't find their watch",
                "who is trying to sell a dragon heart",
                "who wants to spread the word about their god",
                "who is trying to write a love ballad",
                "searching for redemption",
                "who wants to see the next sunrise",
                "who longs to be the strongest person alive",
                "hired to kill a party member",
                "who compulsively judges other's fashion sense",
                "who is trying to build a time machine",
                "who is on a quest to kill monsters",
                "who is trying to do good",
                "who is trying to sell some fruit",
                "who is on the run from prison",
                "who needs to blood of 30 crows",
                "who wants to learn Common",
                "who wants to go on an adventure",
                "who is peddling bags of a medicinal root",
                "who needs to spread their father's ashes",
                "who is hoping to run for public office",
                "who seeks a new owner for their pet owl",
                "who is looking for their dog. Have you seen their dog?",
                "who doesn't let anyone get in their way",
                "who is hunting for ancient relics in old forgotten tombs",
                "who is looking for inspiration for their new novel" #this is the end of the random encounters book
]