item_list = ["Sword",
             "Shield",
             "Hair Brush",
             "Mug",
             "Hat",
             "Book",
             "Rope",
             "Jar",
             "Sock",
             "Bag",
             "Satchel",
             "flute",
             "boots",
             "chalk",
             "cloak",
             "ring",
             "box",
             "chest",
             "staff",
             "arrow",
             "bow",
             "spear",
             "javelin",
             "horse shoe",
             "paper",
             "candle",
             "sack",
             "map",
             "hoe",
             "horn",
             "drum",
             "pipe",
             "axe",
             "pot",
             "squash",
             "nut",
             "mask",
             "symbol",
             "necklace",
             "arm band",
             "cloak",
             "glove",
             "sock",
             "saw",
             "chisel",
             "scroll tube",
             "torch",
             "bean",
             "snake",
             "seed",
             "perfume bottle",
             "knife",
             "blanket",
             "broom",
             "linen",
             "sundial",
             "calendar",
             "mirror",
             "bread",
             "fishing pole",
             "net",
             "canned fruit",
             "soap",
             "stone",
             "lamp",
             "matches",
             "honey",
             "dice",
             "tongs",
             "crowbar",
             "glasses",
             "goggles",
             "stool",
             "chair",
             "table",
             "scroll",
             "wine bottle",
             "jewel",
             "coin",
             "notebook",
             "skirt",
             "crown",
             "circlet",
             "braclet",
             "fish",
             "salt",
             "mushroom",
             "lute",
             "fork",
             "spoon",
             "jar",
             "piano",
             "window",
             "tube",
             "purse",
             "jug",
             "brush",
             "key",
             "spy glass",
             "cloth",
             "drum stick"
             ]