useless_item_list = [
	"A 2 foot iron key with a grinning skull for a bow",
	"A large hourglass in which the sand seems to flow from the bottom to the top",
	"A pouch of almond shaped...seeds? They taste terrible, but are not poisonous. They are not magical but are unidentifiable. They are eggs..of some type...",
	"A human skull painted with swirls of bloody paint. The skull is not magical, but you swear that you can hear unintelligable whispering comming from it.",
	"A large conch shell that randomly makes the sound of crashing waves.",
	"A 1 foot cube that appears to be on fire. It is cool to the touch and gives off no effective light.",
	"A dagger that looks vicious and deadly, but whenever it touches anything organic, it goes all rubbery and dull making it ineffective.",
	"A beautifuly-constructed french horn that makes no noise no matter how hard you try",
	"An intricately carved wand etched with runic symbols and tipped with a glowing yellow sphere made out of crystal. Nothing ever happens. The wand just vibrates in your hand uncomfortably",
	"A hand crafted mechanical compass that never points in the correct cardinal direction",
	"A silver pitcher that leaks so severly that it cannot be effectively used, even though there are no visible holes in it.",
	"A styleish hat that refuses to be worn. When placed on your head it transports to another place on your body or on one of your bags. Once you have touched it, you cannot be rid of it.",
	"An expertly carved long bow. It refuses to shoot an arrow more than a couple feet. The amunition supply slumps to the ground after being fired.",
	"A 5 foot oval mirror with a simple wooden frame. It casts no refleciton, the area inside the mirror is simply a dull silver color",
	"A  very plush and cushy bedroll that causes anyone who sleeps in it to be unconfortably itchy",
	"A forgery kit that even though looks to be quite compitent, can only make forgieries that are easily unidentifiable",
	"A stick of gold sealing wax that never melts",
	"A pack of distinctive playing cards that bear distinctive marks an and numbers before the game is started. Once the game starts, they all go  blank",
	"An expensive pack that holds marbles that are not round. They do not roll and when placed on the ground, they will stay in place",
	"An exquisite hand bell. The ringer will move, but will not make contact with the side of the bell",
	"A stool that is made out of solid (fools) gold",
	"A blue liquid in a potion bottle. Has the effect that when it is injested, the person will feel less thirsty.",
	"Ring of invisibility. The ring turns invisible when worn.",
	"A glowing rock. Only glows when it is sunny.",
	"A very sharp sword. It looks like it is sharp enough to cut stone...but only the handle is sharp",
	"A waterbottle that is always full of water... but its ocean water.",
	"A feather from a black raven. It is exceptionally heavy for a feather",
	"A rock that is perfectly round and smooth. When thrown it will ALWAYS land on another rock",
	"A set of dumbells that look exceptionally heavy but they are as heavy as a feather",
	"A pocketwatch that looks perfectly normal and slightly magical, but it only goes backwords. On the watch is written the words \"may you always remember...\"",
]