color_list = ["Clear",
				"Blue",
				"Green",
				"Red",
				"Pale Green",
				"Sky Blue",
				"Pink",
				"White",
				"Black",
				"Dark Grey",
				"Light Grey",
				"Yellow",
				"Orange",
				"Gold",
				"Rainbow",
				"Bronze",
				"Metalic",
				"Silver",
				"Purple",
				"Brown",
				"Dark Red",
				"Blood Red",
				"Rainbow",
				"Purple",
				"Bone White",
				"Fleshy"
				]