side_effect_list = ["Nothing bad at all!",
					"Puts the user to sleep",
					"Rapid hair growth all over the body",
					"Bleeding from the eyes",
					"Vivid hallucinations",
					"Flashbacks of your own eventual demise",
					"The skin to crack and appear distorted",
					"Spots to grow on the skin",
					"Diarrhoea that starts after the main effect fades",
					"Vomiting that starts after the main effect fades",
					"Blurred Vision",
					"Blindness",
					"Deafness",
					"Mute",
					"Health loss via rapid bleeding (take 2d8 damage)",
					# "A sudden horrific accent",
					"The irresistible urge to dance",
					"The hearing of demons",
					"Loss of balance",
					"Everything tasting like dirt for some time",
					"Excessive drooling",
					"Loss of intelligence",
					"Loss of strength",
					"Loss of speed",
					"Loss of charisma",
					"Genuine happiness",
					"Irresistable Hunger after the main effect ends",
					"Irresistable Thirst after the main effect ends",
					"Trouble breathing",
					"Sudden Moustache",
					"Sudden Beard",
					# "Poisoning",
					# "Petrification",
					# "Stunning",
					"Immobilisation",
					# "Increased libido",
					"Fidgeting",
					"Itchiness",
					"Rashes on the scalp",
					"Rashes on hands",
					"Attracts bears (if nearby)",
					"Magically covered in dirt",
					"Horrifying stench",
					"Baldness",
					"Swelling",
					"Loss of a random item",
					# "Curses",
					"3d4 Fire Damage",
					"3d4 Poison Damage",
					"3d4 Lightning Damage",
					"Healing Resistance",
					"Weakness to a magical damage type",
					"Weakness to physical damage",
					"Feelings of Guilt (disadvantage on int and wisdom rolls)",
					"Feelings of Anxiety(disadvantage on int and wisdom rolls)",
					"Feelings of Shame(disadvantage on int and wisdom rolls)",
					"Sneezing (disadvantage on dex, str, and con rolls)",
					# "Uncontrollable crying",
					# "Need to sing heroic music",
					"Urge to hug",
					"Kleptomania",
					"Burping",
					"Loss of smell",
					"Insomnia",
					"Paranoia",
					"Bad luck (disadvantage on luck oriented rolls)",
					"Summons imps that want to kill you",
					"Summons angry bees",
					"Fear of water",
					"Fear of nature",
					"Fear of party members",
					"Temporary madness",
					"Total Relaxation",
					"Appreciation of colours and sound",
					"Tripping the hell out",
					# "Painful lust",
					"Light headedness",
					"Increased confidence",
					"Recklessness (-2 wisdom)",
					"Rage",
					"Sadness (-2 wisdom)",
					# "Dizziness",
					"Pain, take 1d4 damage",
					# "Slight possession",
					"Allergic reaction to your favourite food",
					"Strongly believe you’re someone else in the party",
					# "Severe debt",
					"Grumpiness",
					"Muscle spasms (-2 con)",
					"A bloated feeling",
					"A cold (-2 con)",
					"A fever (-2 con)",
					"Becoming strangely light",
					"Weakness (-2 strength)",
					"The urge to fight",
					"The need to make friends",
					"Nausea (-2 con)",
					"Mood swings",
					# "Addiction",
					"Need for booze (when main effect ends)",
					"Drunkeness (disadvantage on all rolls)",
					"Coughing (-2 con)",
					"Speach is not understandable",
					"Slight aches",
					"A bad taste for some time",
					"Giddiness",
					"Laughter"
					]