appearance_list = ["Flecks of colour",
					"Swirls of colour",
					"Fizzing bubbles",
					"Bubbles suspended in it",
					"Leaves and flowers in it",
					"A bright glow",
					"A soft glow",
					"Stripes of colour",
					"A cloudy murkiness",
					"Flecks of Blood within it",
					"Dirt floating in it",
					"Chunks of metal in it",
					"Steam coming from it",
					"Constantly moving and shifting liquid",
					"Glitter suspended in the liquid",
					"Sparkles of light coming from the bottle",
					"Two eyes suspended in the liquid",
					"Darkness surrounding the bottle",
					"Hairline cracks in the bottle"
]