#For a good list of these, see this website: https://bankuei.wordpress.com/2013/06/23/big-list-of-combat-stakes/

encouter_spice_list = [
    "If magic happens aroudn the enemies, then they will do a wild magic surge at the beggining of their next turn",
    "There is a TON of REALLY low health enemies (maybe rats?)",
    "Combat is happening in a silenced area, there is some trigger to turn it off, but it is hard to do",
    "Need to get to a portal in X amount of turns or (insert some consiquence here)",
    "Necromancer (or someething else) is controlling a large amount of minions, need to take him out",
    "Need to capture at least one of the enemies alive",
    "Enemies are fleeing, need to stop them from running away for (insert reason here)",
    "There are gaurds in the area, need to defeat an enemy without the gaurds hearing or seeing",
    "Any physical damage will backfire, need to defeat the enemies with only magic",
    "The enemies are mirror images of you, need to defeat your own mirror before you can attack another mirror",
    "The enimies have hostages, have to get hte hostages away before they are killed",
    "The enimies are trying to take an NPC.",
    "There are 2 factions that are fighting one another",
    "All characters randomly swap positions after every round",
    "Retrieve something. You have to get in, and then get out!",
    "Escape a situation that would result in sudden death",
    "Activate something, aka pull a lever",
    "Lure an enemy to a specific point",
    "Delayed Super spells, fireballs do 2x damage, but happen one turn later",
    "Archers shoot exploding arrows that activate wherever the arrow lands next turn",
    "Hold off the oposition until.... (insert stakes here)",
    "Get in, (do something), get out (falsify evidance is my favorite)",
    "One PC is having a nightmare. That PC MUST stay alive, anyone else can die with no consiquence. The fight is almost impossible",
    "The big bad they are fighting gets stronger when hurt",
    "The big bad they are fighting is immortal. It can only be trapped",
    "Player attacks only stun the boss. Some outside mechanic must be used to kill it (lava, env hazards, light, ect)",
    "In a certain dungon, all attacks are ranged attacks (aka a sword strike becomes throwm)",
    "One PC becomes gigantic, and all other ones become stronger. The gigantic one deals 4x damage and the smaller ones deal 1/4x damage",
    "Healing and damage is swapped. Healing spells hurt and damaing actions heal",
    "The party shares abilities. Aka the fighter can cast the wizards spells",
    "The party cannot cast cantrips",
]
